/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmat;

import funciones.Usuario;
import funciones.ConexionDb;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rsscalelabel.RSScaleLabel;

/**
 *
 * @author Administrador
 */
public class AdministradorUsuarios extends javax.swing.JFrame {

    public String usuarioactivo;
    public String idusuarioactivo;
    public String textomonitor = "Usuarios";
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Imagen", "JPG");
    public String rutaimagen = "";
    String idperfil = null;
    Icon icon = null;
    Object[] NombreColumnas = {
        "ID",
        "USUARIO",
        "CONTRASEÑA",
        "PERFIL",
        "ASIGNACION",
        "ACTIVO"
    };

    /**
     * Creates new form Contenedor
     */
    public AdministradorUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        JlMonitorNombre.setText(textomonitor);
        monitorinformacion.setText(usuarioactivo);
        rutaimagen = "";
        CargaTabla();
        Combobox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JlMonitorNombre = new javax.swing.JLabel();
        BtnUsuarios = new javax.swing.JButton();
        BtnEquipos = new javax.swing.JButton();
        BtnConcursos = new javax.swing.JButton();
        BtnResultados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        IdUsuarioAlta = new javax.swing.JLabel();
        UsuarioAlta = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LabelUsuario = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        ContrasenaAlta = new javax.swing.JTextField();
        LabelContrasena = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        BoxPerfilAlta = new javax.swing.JComboBox<>();
        AsignacionAlta = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        LabelAsignacion = new javax.swing.JLabel();
        ChkActivarAlta = new javax.swing.JCheckBox();
        BtnEliminarAltaUsuario = new javax.swing.JButton();
        BtnGuardaAltaUsuario = new javax.swing.JButton();
        BtnLimpiaAltaUsuario = new javax.swing.JButton();
        BtnImprimeReporteUsuarios = new javax.swing.JButton();
        IcoBuscar = new javax.swing.JLabel();
        BusquedaUsuario = new javax.swing.JTextField();
        FotoUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        monitorinformacion = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, 170, -1));

        JlMonitorNombre.setBackground(new java.awt.Color(255, 255, 255));
        JlMonitorNombre.setFont(new java.awt.Font("Decker", 1, 22)); // NOI18N
        JlMonitorNombre.setForeground(new java.awt.Color(102, 102, 102));
        JlMonitorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(JlMonitorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        BtnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        BtnUsuarios.setBorder(null);
        BtnUsuarios.setContentAreaFilled(false);
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        BtnEquipos.setBackground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        BtnEquipos.setBorder(null);
        BtnEquipos.setContentAreaFilled(false);
        BtnEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEquipos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(BtnEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        BtnConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setForeground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_concurso_100.png"))); // NOI18N
        BtnConcursos.setBorder(null);
        BtnConcursos.setContentAreaFilled(false);
        BtnConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConcursosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BtnResultados.setBackground(new java.awt.Color(255, 255, 255));
        BtnResultados.setForeground(new java.awt.Color(255, 255, 255));
        BtnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        BtnResultados.setBorder(null);
        BtnResultados.setContentAreaFilled(false);
        BtnResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnResultados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResultadosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        TablaUsuarios.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        TablaUsuarios.setForeground(new java.awt.Color(153, 153, 153));
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 750, 540));

        IdUsuarioAlta.setBackground(new java.awt.Color(255, 255, 255));
        IdUsuarioAlta.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        IdUsuarioAlta.setForeground(new java.awt.Color(102, 102, 102));
        IdUsuarioAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(IdUsuarioAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 20));

        UsuarioAlta.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        UsuarioAlta.setForeground(new java.awt.Color(153, 153, 153));
        UsuarioAlta.setText("Nuevo Usuario");
        UsuarioAlta.setBorder(null);
        UsuarioAlta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuarioAltaFocusGained(evt);
            }
        });
        UsuarioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAltaActionPerformed(evt);
            }
        });
        jPanel2.add(UsuarioAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 280, -1));

        LabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        LabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelUsuario.setText("Usuario:");
        jPanel2.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 40));

        LabelId.setBackground(new java.awt.Color(255, 255, 255));
        LabelId.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        LabelId.setForeground(new java.awt.Color(102, 102, 102));
        LabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelId.setText("ID:");
        jPanel2.add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));

        ContrasenaAlta.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        ContrasenaAlta.setForeground(new java.awt.Color(153, 153, 153));
        ContrasenaAlta.setText("Ingrese Contraseña");
        ContrasenaAlta.setBorder(null);
        ContrasenaAlta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContrasenaAltaFocusGained(evt);
            }
        });
        ContrasenaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaAltaActionPerformed(evt);
            }
        });
        jPanel2.add(ContrasenaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 180, 40));

        LabelContrasena.setBackground(new java.awt.Color(255, 255, 255));
        LabelContrasena.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        LabelContrasena.setForeground(new java.awt.Color(102, 102, 102));
        LabelContrasena.setText("Contraseña:");
        jPanel2.add(LabelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 40));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 280, -1));

        BoxPerfilAlta.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxPerfilAlta.setForeground(new java.awt.Color(102, 102, 102));
        BoxPerfilAlta.setMaximumRowCount(1000);
        BoxPerfilAlta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Perfil" }));
        BoxPerfilAlta.setBorder(null);
        BoxPerfilAlta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxPerfilAltaFocusGained(evt);
            }
        });
        BoxPerfilAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxPerfilAltaMouseClicked(evt);
            }
        });
        jPanel2.add(BoxPerfilAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 280, 40));

        AsignacionAlta.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        AsignacionAlta.setForeground(new java.awt.Color(153, 153, 153));
        AsignacionAlta.setText("Usuario Asignado a:");
        AsignacionAlta.setBorder(null);
        AsignacionAlta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AsignacionAltaFocusGained(evt);
            }
        });
        AsignacionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionAltaActionPerformed(evt);
            }
        });
        jPanel2.add(AsignacionAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 180, 40));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 280, -1));

        LabelAsignacion.setBackground(new java.awt.Color(255, 255, 255));
        LabelAsignacion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        LabelAsignacion.setForeground(new java.awt.Color(102, 102, 102));
        LabelAsignacion.setText("Asignación:");
        jPanel2.add(LabelAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 40));

        ChkActivarAlta.setBackground(new java.awt.Color(255, 255, 255));
        ChkActivarAlta.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        ChkActivarAlta.setForeground(new java.awt.Color(102, 102, 102));
        ChkActivarAlta.setSelected(true);
        ChkActivarAlta.setText("Activar Usuario");
        ChkActivarAlta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(ChkActivarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, 40));

        BtnEliminarAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminarAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Eliminar.png"))); // NOI18N
        BtnEliminarAltaUsuario.setBorder(null);
        BtnEliminarAltaUsuario.setBorderPainted(false);
        BtnEliminarAltaUsuario.setContentAreaFilled(false);
        BtnEliminarAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminarAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 720, -1, -1));

        BtnGuardaAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardaAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Guardar.png"))); // NOI18N
        BtnGuardaAltaUsuario.setBorder(null);
        BtnGuardaAltaUsuario.setBorderPainted(false);
        BtnGuardaAltaUsuario.setContentAreaFilled(false);
        BtnGuardaAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGuardaAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardaAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuardaAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 720, -1, -1));

        BtnLimpiaAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiaAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Limpiar.jpg"))); // NOI18N
        BtnLimpiaAltaUsuario.setBorder(null);
        BtnLimpiaAltaUsuario.setBorderPainted(false);
        BtnLimpiaAltaUsuario.setContentAreaFilled(false);
        BtnLimpiaAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiaAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiaAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLimpiaAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, -1, -1));

        BtnImprimeReporteUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnImprimeReporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Imprimir.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setBorder(null);
        BtnImprimeReporteUsuarios.setBorderPainted(false);
        BtnImprimeReporteUsuarios.setContentAreaFilled(false);
        BtnImprimeReporteUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImprimeReporteUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimeReporteUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnImprimeReporteUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, -1, -1));

        IcoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Search_32px.png"))); // NOI18N
        jPanel2.add(IcoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

        BusquedaUsuario.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BusquedaUsuario.setForeground(new java.awt.Color(153, 153, 153));
        BusquedaUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BusquedaUsuario.setText("Realizar Busqueda");
        BusquedaUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        BusquedaUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BusquedaUsuarioFocusLost(evt);
            }
        });
        BusquedaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaUsuarioMouseClicked(evt);
            }
        });
        BusquedaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BusquedaUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BusquedaUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusquedaUsuarioKeyTyped(evt);
            }
        });
        jPanel2.add(BusquedaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 370, 40));

        FotoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        FotoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        FotoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        FotoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoUsuarioMouseClicked(evt);
            }
        });
        jPanel2.add(FotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1090, 860));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        monitorinformacion.setBackground(new java.awt.Color(255, 255, 255));
        monitorinformacion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        monitorinformacion.setForeground(new java.awt.Color(102, 102, 102));

        BtnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_minimisar_32px.png"))); // NOI18N
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
        });

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cerrar_32px.png"))); // NOI18N
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(monitorinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(BtnMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCerrar)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitorinformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMinimizar)
                    .addComponent(BtnCerrar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void BtnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMouseClicked
        JlMonitorNombre.setText("Usuarios");
        AdministradorUsuarios pantallausuarios = new AdministradorUsuarios();
        pantallausuarios.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallausuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnUsuariosMouseClicked

    private void BtnEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEquiposMouseClicked
        JlMonitorNombre.setText("Equipos");
        AdministradorEquipos pantallaclientes = new AdministradorEquipos();
        pantallaclientes.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaclientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEquiposMouseClicked

    private void BtnConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConcursosMouseClicked
        JlMonitorNombre.setText("Concursos");
        AdministradorConcursos pantallaproveedores = new AdministradorConcursos();
        pantallaproveedores.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaproveedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnConcursosMouseClicked

    private void BtnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResultadosMouseClicked
        JlMonitorNombre.setText("Resultados");
        AdministradorResultados pantallainventario = new AdministradorResultados();
        pantallainventario.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallainventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnResultadosMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel3MouseMoved

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Cerrar Esta Ventana?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void UsuarioAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAltaActionPerformed

    private void ContrasenaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaAltaActionPerformed

    private void AsignacionAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignacionAltaActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        if (evt.getButton() == 1) {
            int id = TablaUsuarios.getSelectedRow();
            try {
                ResultSet consulta;
                ConexionDb db = new ConexionDb();
                Statement st = db.Conecxion();
                consulta = db.realizarConsulta("SELECT * FROM Consulta_Usuarios WHERE ID = "
                        + TablaUsuarios.getValueAt(id, 0), st);
                consulta.next();
                IdUsuarioAlta.setText(consulta.getString("ID"));
                UsuarioAlta.setText(consulta.getString("USUARIO"));
                ContrasenaAlta.setText((String) TablaUsuarios.getValueAt(id, 2));
                DefaultComboBoxModel cbox = new DefaultComboBoxModel();
                cbox.addElement(consulta.getString("PERFIL"));
                BoxPerfilAlta.setModel(cbox);
                String idusuario = IdUsuarioAlta.getText();
                CargaImagen(idusuario);
                if ("1".equals(consulta.getString("ACTIVO"))) {
                    ChkActivarAlta.setSelected(true);
                } else {
                    ChkActivarAlta.setSelected(false);
                }
                AsignacionAlta.setText(consulta.getString("ASIGNACION"));
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void BtnImprimeReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimeReporteUsuariosActionPerformed
        /**
         * PDFusuarios imprimepdf = new PDFusuarios();
        Date fecha = new Date();
        fecha.getTime();
        imprimepdf.GeneraPDF("REPORTE DE USUARIOS", "ESTE ES EL REPORTE DE USUARIOS", "Guadalajara Jal " + fecha,
                "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Documents\\NetBeansProjects\\OnlineStore\\src\\Imagenes\\logo.png",
                "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Desktop\\Prueba.pdf", null, TablaUsuarios);
        **/
                try {
            ConexionDb cn = new ConexionDb();
            Connection cnsql = DriverManager.getConnection(cn.urlconexion, cn.usuario, cn.password);
            JasperReport reporte;
            String path = (getClass().getResource("../Reportes/ERP-Usuarios.jasper").getPath());
            Map parametros = new HashMap();
            parametros.put("tabla","Usuarios");
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, parametros, cnsql);
            JasperViewer vistareporte = new JasperViewer(jprint, false);
            vistareporte.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            vistareporte.setVisible(true);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(AdministradorUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnImprimeReporteUsuariosActionPerformed

    private void BtnGuardaAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardaAltaUsuarioActionPerformed
        String imagen = this.rutaimagen;
        String id = IdUsuarioAlta.getText();
        String Usuario = UsuarioAlta.getText();
        String Contrasena = ContrasenaAlta.getText();
        boolean Check = ChkActivarAlta.isSelected();
        String Activado;
        String Asignacion = AsignacionAlta.getText();
        idperfil = (String) BoxPerfilAlta.getSelectedItem();
        Usuario Perfil = new Usuario();
        idperfil = Perfil.ConsultaPerfil(idperfil);
        
        int foto = 1;
        if(imagen.equals("")){
            foto = 0;
        }

        if (Check != true) {
            Activado = "0";
        } else {
            Activado = "1";
        }

        if (id.isEmpty()) {

            //** Mensaje que mostrava si check estaba activo JOptionPane.showMessageDialog(this, Activo);
            if ((Usuario.isEmpty() || Contrasena.isEmpty() || idperfil.isEmpty() || Asignacion.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Todos los Campos deben ser llenados");
            } else {
                Usuario alta = new Usuario();
                alta.GuardaUsuario(Usuario, Contrasena, idperfil, Activado, Asignacion, rutaimagen);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Usuario se Guardo Correctamente");
            }
        } else {
            //Se realiza la Modificación del Registro
            if ((Usuario.isEmpty() || Contrasena.isEmpty() || idperfil.isEmpty() || Asignacion.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Todos los Campos deben ser llenados");
            } else {
                Usuario modificacion = new Usuario();
                if (Contrasena.equals("******")) {
                    modificacion.SinContrasena(id, Usuario, idperfil, Activado, Asignacion, imagen, foto);
                } else {
                    modificacion.ModificaUsuario(id, Usuario, Contrasena, idperfil, Activado, Asignacion, imagen, foto);
                }
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Usuario se Modificó Correctamente");
            }
        }
    }//GEN-LAST:event_BtnGuardaAltaUsuarioActionPerformed

    private void BtnLimpiaAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiaAltaUsuarioActionPerformed
        LimpiaCampos();
    }//GEN-LAST:event_BtnLimpiaAltaUsuarioActionPerformed

    private void BtnEliminarAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarAltaUsuarioActionPerformed
        String Id = IdUsuarioAlta.getText();
        String Usuario = UsuarioAlta.getText();
        String Perfil = (String) BoxPerfilAlta.getSelectedItem();
        String Asignacion = AsignacionAlta.getText();

        Object[] opciones = {"ACEPTAR", "CANCELAR"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "Se Eliminará " + Usuario + " Asignado a: "
                + Asignacion, "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, "ACEPTAR");
        if (eleccion == JOptionPane.YES_OPTION) {
            int confirmar = JOptionPane.YES_OPTION;

            if ("ADMIN".equals(Perfil.toUpperCase().trim())) {
                confirmar = JOptionPane.showOptionDialog(rootPane, "El Usuario es Administrador, Desea Eliminarlo", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, "ACEPTAR");
            }

            if (confirmar == JOptionPane.YES_OPTION) {
                Usuario eliminacion = new Usuario();
                eliminacion.EliminaUsuario(Id);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Usuario se Eliminó Correctamente");
            }
        }

    }//GEN-LAST:event_BtnEliminarAltaUsuarioActionPerformed

    private void UsuarioAltaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioAltaFocusGained
        UsuarioAlta.setText("");
    }//GEN-LAST:event_UsuarioAltaFocusGained

    private void ContrasenaAltaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContrasenaAltaFocusGained
        ContrasenaAlta.setText("");
    }//GEN-LAST:event_ContrasenaAltaFocusGained

    private void AsignacionAltaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AsignacionAltaFocusGained
        AsignacionAlta.setText("");
    }//GEN-LAST:event_AsignacionAltaFocusGained

    private void BoxPerfilAltaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxPerfilAltaFocusGained
        Combobox();
    }//GEN-LAST:event_BoxPerfilAltaFocusGained

    private void BoxPerfilAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxPerfilAltaMouseClicked
        Combobox();
    }//GEN-LAST:event_BoxPerfilAltaMouseClicked

    private void BusquedaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaUsuarioKeyPressed
        Usuario Busqueda = new Usuario();
        Busqueda.BusquedaUsuario(BusquedaUsuario.getText(), TablaUsuarios, NombreColumnas);
    }//GEN-LAST:event_BusquedaUsuarioKeyPressed

    private void BusquedaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaUsuarioMouseClicked
        BusquedaUsuario.setText("");
        Usuario Busqueda = new Usuario();
        Busqueda.BusquedaUsuario(BusquedaUsuario.getText(), TablaUsuarios, NombreColumnas);
    }//GEN-LAST:event_BusquedaUsuarioMouseClicked

    private void BusquedaUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaUsuarioKeyTyped

    private void BusquedaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaUsuarioKeyReleased
        Usuario Busqueda = new Usuario();
        Busqueda.BusquedaUsuario(BusquedaUsuario.getText(), TablaUsuarios, NombreColumnas);
    }//GEN-LAST:event_BusquedaUsuarioKeyReleased

    private void BusquedaUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusquedaUsuarioFocusLost
        BusquedaUsuario.setText("Realizar Busqueda");
    }//GEN-LAST:event_BusquedaUsuarioFocusLost

    private void FotoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoUsuarioMouseClicked
        javax.swing.JFileChooser ventana = new javax.swing.JFileChooser();
        ventana.setDialogTitle("Buscar Foto del Usuario");
        int opcion = ventana.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            String fil = ventana.getSelectedFile().getPath();
            RSScaleLabel.setScaleLabel(FotoUsuario, ventana.getSelectedFile().toString());
            rutaimagen = ventana.getSelectedFile().toString();
        }
    }//GEN-LAST:event_FotoUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AsignacionAlta;
    private javax.swing.JComboBox<String> BoxPerfilAlta;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JButton BtnConcursos;
    private javax.swing.JButton BtnEliminarAltaUsuario;
    private javax.swing.JButton BtnEquipos;
    private javax.swing.JButton BtnGuardaAltaUsuario;
    private javax.swing.JButton BtnImprimeReporteUsuarios;
    private javax.swing.JButton BtnLimpiaAltaUsuario;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JButton BtnResultados;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JTextField BusquedaUsuario;
    private javax.swing.JCheckBox ChkActivarAlta;
    private javax.swing.JTextField ContrasenaAlta;
    private javax.swing.JLabel FotoUsuario;
    private javax.swing.JLabel IcoBuscar;
    private javax.swing.JLabel IdUsuarioAlta;
    private javax.swing.JLabel JlMonitorNombre;
    private javax.swing.JLabel LabelAsignacion;
    private javax.swing.JLabel LabelContrasena;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JTextField UsuarioAlta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel monitorinformacion;
    // End of variables declaration//GEN-END:variables

    public void recibeusuario(String idusuario, String usuario) {
        idusuarioactivo = idusuario;
        usuarioactivo = usuario;
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    public void mandadatos() {
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    private void CargaTabla() {
        try {
            String activo;
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            consulta = db.realizarConsulta("SELECT ID, USUARIO, CONTRASEÑA = '******'"
                    + ",PERFIL, ACTIVO, ASIGNACION FROM USUARIOS", st);
            DefaultTableModel tabla = new DefaultTableModel(NombreColumnas, WIDTH);
            TablaUsuarios.setModel(tabla);
            while (consulta.next()) {
                activo = consulta.getString("ACTIVO");
                if ("1".equals(activo)) {
                    activo = "ACTIVO";
                } else {
                    activo = "DESACTIVADO";
                }
                tabla.addRow(new Object[]{consulta.getString("ID"), consulta.getString("USUARIO"), consulta.getString("CONTRASEÑA"),
                    consulta.getString("PERFIL"), consulta.getString("ASIGNACION"), activo});
            }
            tabla.removeRow(0);
        } catch (SQLException ex) {
            Logger.getLogger(AdministradorUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LimpiaCampos() {
        IdUsuarioAlta.setText("");
        UsuarioAlta.setText("Nuevo Usuario");
        ContrasenaAlta.setText("Ingrese Contraseña");
        DefaultComboBoxModel cbox = new DefaultComboBoxModel();
        cbox.addElement("Selecciona un Perfil");
        BoxPerfilAlta.setModel(cbox);
        ChkActivarAlta.setSelected(false);
        AsignacionAlta.setText("Usuario Asignado a:");
        BusquedaUsuario.setText("Realizar Busqueda");
        FotoUsuario.setIcon(icon);
        rutaimagen = "";
        idperfil = null;
    }

    private void Combobox() {
        try {
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            //Statement insertcombox = db.Conecxion();
            DefaultComboBoxModel cbox = new DefaultComboBoxModel();
            cbox.addElement("Selecciona un Perfil");
            consulta = db.realizarConsulta("SELECT * FROM PERFILES", st);
            while (consulta.next()) {
                idperfil = consulta.getString("ID");
                cbox.addElement(consulta.getObject("PERFIL"));
            }
            BoxPerfilAlta.setModel(cbox);
        } catch (SQLException e) {
        }
    }

    private void CargaImagen(String idproducto) {
        ConexionDb db = new ConexionDb();
        Statement st = db.Conecxion();
        ResultSet consulta;

        try {
            consulta = db.realizarConsulta("SELECT ID,IMAGEN2 FROM USUARIOS WHERE ID = " + idproducto, st);
            consulta.next();
            String imgst = consulta.getString("IMAGEN2");
            if (imgst == null) {
                FotoUsuario.setIcon(icon);
            } else {
                Blob imagenproducto = consulta.getBlob("IMAGEN2");
                byte[] recuperarimagen = imagenproducto.getBytes(1, (int) imagenproducto.length());
                BufferedImage imgproducto = ImageIO.read(new ByteArrayInputStream(recuperarimagen));
                Image imagencompleta = imgproducto.getScaledInstance(FotoUsuario.getWidth(), FotoUsuario.getHeight(), Image.SCALE_SMOOTH);
                FotoUsuario.setIcon(new ImageIcon(imagencompleta));
            }
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AdministradorUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
