/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmat;

import funciones.ConexionDb;
import funciones.Equipo;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class AdministradorEquipos extends javax.swing.JFrame {

    public String usuarioactivo;
    public String idusuarioactivo;
    public String textomonitor = "Equipos";
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Imagen", "JPG");
    public String rutaimagen = "";
    Icon icon = null;
    Object[] NombreColumnas = {
        "ID",
        "NOMBRE",
        "UNIVERSIDAD",
        "CAPITAN"
    };

    /**
     * Creates new form Contenedor
     */
    public AdministradorEquipos() {
        initComponents();
        this.setLocationRelativeTo(null);
        JlMonitorNombre.setText(textomonitor);
        monitorinformacion.setText(usuarioactivo);
        rutaimagen = "";
        CargaTabla();
        ComboboxUniversidad();
        ComboboxCapitan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JlMonitorNombre = new javax.swing.JLabel();
        BtnUsuarios = new javax.swing.JButton();
        BtnEquipos = new javax.swing.JButton();
        BtnConcursos = new javax.swing.JButton();
        BtnResultados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEquipos = new javax.swing.JTable();
        IdEquipo = new javax.swing.JLabel();
        InputEquipo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LabelEquipo = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        BoxUniversidad = new javax.swing.JComboBox<>();
        BoxCapitan = new javax.swing.JComboBox<>();
        BtnEliminarAltaUsuario = new javax.swing.JButton();
        BtnGuardaAltaUsuario = new javax.swing.JButton();
        BtnLimpiaAltaUsuario = new javax.swing.JButton();
        BtnImprimeReporteUsuarios = new javax.swing.JButton();
        IcoBuscar = new javax.swing.JLabel();
        BusquedaEquipo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        monitorinformacion = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, 170, -1));

        JlMonitorNombre.setBackground(new java.awt.Color(255, 255, 255));
        JlMonitorNombre.setFont(new java.awt.Font("Decker", 1, 22)); // NOI18N
        JlMonitorNombre.setForeground(new java.awt.Color(102, 102, 102));
        JlMonitorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(JlMonitorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        BtnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        BtnUsuarios.setBorder(null);
        BtnUsuarios.setContentAreaFilled(false);
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        BtnEquipos.setBackground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        BtnEquipos.setBorder(null);
        BtnEquipos.setContentAreaFilled(false);
        BtnEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEquipos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(BtnEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        BtnConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setForeground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_concurso_100.png"))); // NOI18N
        BtnConcursos.setBorder(null);
        BtnConcursos.setContentAreaFilled(false);
        BtnConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConcursosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BtnResultados.setBackground(new java.awt.Color(255, 255, 255));
        BtnResultados.setForeground(new java.awt.Color(255, 255, 255));
        BtnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        BtnResultados.setBorder(null);
        BtnResultados.setContentAreaFilled(false);
        BtnResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnResultados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResultadosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        TablaEquipos.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        TablaEquipos.setForeground(new java.awt.Color(153, 153, 153));
        TablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEquipos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 750, 540));

        IdEquipo.setBackground(new java.awt.Color(255, 255, 255));
        IdEquipo.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        IdEquipo.setForeground(new java.awt.Color(102, 102, 102));
        IdEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(IdEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 20));

        InputEquipo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        InputEquipo.setForeground(new java.awt.Color(153, 153, 153));
        InputEquipo.setText("Nombre del Equipo");
        InputEquipo.setBorder(null);
        InputEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputEquipoFocusGained(evt);
            }
        });
        InputEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEquipoActionPerformed(evt);
            }
        });
        jPanel2.add(InputEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 280, -1));

        LabelEquipo.setBackground(new java.awt.Color(255, 255, 255));
        LabelEquipo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        LabelEquipo.setForeground(new java.awt.Color(102, 102, 102));
        LabelEquipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelEquipo.setText("Equipo:");
        jPanel2.add(LabelEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 40));

        LabelId.setBackground(new java.awt.Color(255, 255, 255));
        LabelId.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        LabelId.setForeground(new java.awt.Color(102, 102, 102));
        LabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelId.setText("ID:");
        jPanel2.add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));

        BoxUniversidad.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxUniversidad.setForeground(new java.awt.Color(102, 102, 102));
        BoxUniversidad.setMaximumRowCount(1000);
        BoxUniversidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignar Universidad" }));
        BoxUniversidad.setBorder(null);
        BoxUniversidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxUniversidadFocusGained(evt);
            }
        });
        BoxUniversidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxUniversidadMouseClicked(evt);
            }
        });
        jPanel2.add(BoxUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 280, 40));

        BoxCapitan.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxCapitan.setForeground(new java.awt.Color(102, 102, 102));
        BoxCapitan.setMaximumRowCount(1000);
        BoxCapitan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asigne Capitan" }));
        BoxCapitan.setBorder(null);
        BoxCapitan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxCapitanFocusGained(evt);
            }
        });
        BoxCapitan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxCapitanMouseClicked(evt);
            }
        });
        jPanel2.add(BoxCapitan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 280, 40));

        BtnEliminarAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminarAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Eliminar.png"))); // NOI18N
        BtnEliminarAltaUsuario.setBorder(null);
        BtnEliminarAltaUsuario.setBorderPainted(false);
        BtnEliminarAltaUsuario.setContentAreaFilled(false);
        BtnEliminarAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminarAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 720, -1, -1));

        BtnGuardaAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardaAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Guardar.png"))); // NOI18N
        BtnGuardaAltaUsuario.setBorder(null);
        BtnGuardaAltaUsuario.setBorderPainted(false);
        BtnGuardaAltaUsuario.setContentAreaFilled(false);
        BtnGuardaAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGuardaAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardaAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuardaAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 720, -1, -1));

        BtnLimpiaAltaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiaAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Limpiar.jpg"))); // NOI18N
        BtnLimpiaAltaUsuario.setBorder(null);
        BtnLimpiaAltaUsuario.setBorderPainted(false);
        BtnLimpiaAltaUsuario.setContentAreaFilled(false);
        BtnLimpiaAltaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiaAltaUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiaAltaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLimpiaAltaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, -1, -1));

        BtnImprimeReporteUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnImprimeReporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Imprimir.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setBorder(null);
        BtnImprimeReporteUsuarios.setBorderPainted(false);
        BtnImprimeReporteUsuarios.setContentAreaFilled(false);
        BtnImprimeReporteUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImprimeReporteUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimeReporteUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnImprimeReporteUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, -1, -1));

        IcoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Search_32px.png"))); // NOI18N
        jPanel2.add(IcoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

        BusquedaEquipo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BusquedaEquipo.setForeground(new java.awt.Color(153, 153, 153));
        BusquedaEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BusquedaEquipo.setText("Realizar Busqueda");
        BusquedaEquipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        BusquedaEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BusquedaEquipoFocusLost(evt);
            }
        });
        BusquedaEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaEquipoMouseClicked(evt);
            }
        });
        BusquedaEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BusquedaEquipoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BusquedaEquipoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusquedaEquipoKeyTyped(evt);
            }
        });
        jPanel2.add(BusquedaEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 370, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1090, 860));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        monitorinformacion.setBackground(new java.awt.Color(255, 255, 255));
        monitorinformacion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        monitorinformacion.setForeground(new java.awt.Color(102, 102, 102));

        BtnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_minimisar_32px.png"))); // NOI18N
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
        });

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cerrar_32px.png"))); // NOI18N
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(monitorinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(BtnMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCerrar)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitorinformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMinimizar)
                    .addComponent(BtnCerrar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void BtnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMouseClicked
        JlMonitorNombre.setText("Usuarios");
        AdministradorUsuarios pantallausuarios = new AdministradorUsuarios();
        pantallausuarios.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallausuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnUsuariosMouseClicked

    private void BtnEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEquiposMouseClicked
        JlMonitorNombre.setText("Equipos");
        AdministradorEquipos pantallaclientes = new AdministradorEquipos();
        pantallaclientes.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaclientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEquiposMouseClicked

    private void BtnConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConcursosMouseClicked
        JlMonitorNombre.setText("Concursos");
        AdministradorConcursos pantallaproveedores = new AdministradorConcursos();
        pantallaproveedores.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaproveedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnConcursosMouseClicked

    private void BtnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResultadosMouseClicked
        JlMonitorNombre.setText("Resultados");
        AdministradorResultados pantallainventario = new AdministradorResultados();
        pantallainventario.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallainventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnResultadosMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel3MouseMoved

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Cerrar Esta Ventana?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void InputEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEquipoActionPerformed

    private void TablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEquiposMouseClicked
        if (evt.getButton() == 1) {
            int id = TablaEquipos.getSelectedRow();
            try {
                ResultSet consulta;
                ConexionDb db = new ConexionDb();
                Statement st = db.Conecxion();
                consulta = db.realizarConsulta("SELECT * FROM Consulta_Equipo WHERE ID = "
                        + TablaEquipos.getValueAt(id, 0), st);
                consulta.next();
                IdEquipo.setText(consulta.getString("Id"));
                InputEquipo.setText(consulta.getString("Nombre"));
                DefaultComboBoxModel CboxUniversidad = new DefaultComboBoxModel();
                CboxUniversidad.addElement(consulta.getString("Universidad"));
                DefaultComboBoxModel CboxCapitan = new DefaultComboBoxModel();
                CboxCapitan.addElement(consulta.getString("Capitan"));
                BoxUniversidad.setModel(CboxUniversidad);
                BoxCapitan.setModel(CboxCapitan);
                String Idequipo = IdEquipo.getText();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_TablaEquiposMouseClicked

    private void BtnImprimeReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimeReporteUsuariosActionPerformed
        /**
         * PDFusuarios imprimepdf = new PDFusuarios(); Date fecha = new Date();
         * fecha.getTime(); imprimepdf.GeneraPDF("REPORTE DE USUARIOS", "ESTE ES
         * EL REPORTE DE USUARIOS", "Guadalajara Jal " + fecha,
         * "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Documents\\NetBeansProjects\\OnlineStore\\src\\Imagenes\\logo.png",
         * "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Desktop\\Prueba.pdf",
         * null, TablaUsuarios);
         *
         */
        try {
            ConexionDb cn = new ConexionDb();
            Connection cnsql = DriverManager.getConnection(cn.urlconexion, cn.usuario, cn.password);
            JasperReport reporte;
            String path = (getClass().getResource("../Reportes/ERP-Equipos.jasper").getPath());
            Map parametros = new HashMap();
            parametros.put("tabla", "Equipos");
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, parametros, cnsql);
            JasperViewer vistareporte = new JasperViewer(jprint, false);
            vistareporte.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            vistareporte.setVisible(true);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(AdministradorEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnImprimeReporteUsuariosActionPerformed

    private void BtnGuardaAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardaAltaUsuarioActionPerformed
        String Id = IdEquipo.getText();
        String Equipo = InputEquipo.getText();
        String Universidad = (String) BoxUniversidad.getSelectedItem();
        String Capitan = (String) BoxCapitan.getSelectedItem();
        Equipo ComboBox = new Equipo();
        Universidad = ComboBox.ConsultaUniversidad(Universidad);
        Capitan = ComboBox.ConsultaCapitan(Capitan);

        if (Id.isEmpty()) {

            //** Mensaje que mostrava si check estaba activo JOptionPane.showMessageDialog(this, Activo);
            if ((Equipo.isEmpty() || Universidad.equals("Asignar Universidad") || Capitan.equals("Asigne Capitan"))) {
                JOptionPane.showMessageDialog(this, "Todos los Campos deben ser llenados");
            } else {
                Equipo Alta = new Equipo();
                Alta.GuardaEquipo(Equipo, Universidad, Capitan);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Equipo se Guardo Correctamente");
            }
        } else {
            //Se realiza la Modificación del Registro
            if ((Equipo.isEmpty() || Universidad.equals("Asignar Universidad") || Capitan.equals("Asigne Capitan"))) {
                JOptionPane.showMessageDialog(this, "Todos los Campos deben ser llenados");
            } else {
                Equipo Modificacion = new Equipo();
                Modificacion.ModificaEquipo(Id, Equipo, Universidad, Capitan);
            }
            CargaTabla();
            LimpiaCampos();
            JOptionPane.showMessageDialog(this, "El Usuario se Modificó Correctamente");
        }
    }//GEN-LAST:event_BtnGuardaAltaUsuarioActionPerformed

    private void BtnLimpiaAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiaAltaUsuarioActionPerformed
        LimpiaCampos();
    }//GEN-LAST:event_BtnLimpiaAltaUsuarioActionPerformed

    private void BtnEliminarAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarAltaUsuarioActionPerformed
        String Id = IdEquipo.getText();
        String Equipo = InputEquipo.getText();
        String Capitan = (String) BoxCapitan.getSelectedItem();
        String Universidad = (String) BoxUniversidad.getSelectedItem();

        Object[] opciones = {"ACEPTAR", "CANCELAR"};
        int Eleccion = JOptionPane.showOptionDialog(rootPane, "Se Eliminará " + Equipo + " Asignado a: "
                + Capitan + " De la Universidad " + Universidad, "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, "ACEPTAR");

        if (Eleccion == JOptionPane.YES_OPTION) {
            int confirmar = JOptionPane.YES_OPTION;

            Equipo Busca = new Equipo();
            int Cursos = Busca.ConsultaCursos(Id);
            if (Cursos > 0) {
                confirmar = JOptionPane.showOptionDialog(rootPane, "El Equipo" + Equipo + "Tiene " + Cursos + "Cursos Asignados, Desea Eliminarlo", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, "ACEPTAR");
            }

            if (confirmar == JOptionPane.YES_OPTION) {
                Equipo eliminacion = new Equipo();
                eliminacion.EliminaUsuario(Id);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Equipo se Eliminó Correctamente");
            }
        }

    }//GEN-LAST:event_BtnEliminarAltaUsuarioActionPerformed

    private void InputEquipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputEquipoFocusGained
        InputEquipo.setText("");
    }//GEN-LAST:event_InputEquipoFocusGained

    private void BoxCapitanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxCapitanFocusGained
        ComboboxCapitan();
    }//GEN-LAST:event_BoxCapitanFocusGained

    private void BoxCapitanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxCapitanMouseClicked
        ComboboxCapitan();
    }//GEN-LAST:event_BoxCapitanMouseClicked

    private void BusquedaEquipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaEquipoKeyPressed
        Equipo Busqueda = new Equipo();
        Busqueda.BusquedaEquipo(BusquedaEquipo.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaEquipoKeyPressed

    private void BusquedaEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaEquipoMouseClicked
        BusquedaEquipo.setText("");
        Equipo Busqueda = new Equipo();
        Busqueda.BusquedaEquipo(BusquedaEquipo.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaEquipoMouseClicked

    private void BusquedaEquipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaEquipoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaEquipoKeyTyped

    private void BusquedaEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaEquipoKeyReleased
        Equipo Busqueda = new Equipo();
        Busqueda.BusquedaEquipo(BusquedaEquipo.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaEquipoKeyReleased

    private void BusquedaEquipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusquedaEquipoFocusLost
        BusquedaEquipo.setText("Realizar Busqueda");
    }//GEN-LAST:event_BusquedaEquipoFocusLost

    private void BoxUniversidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxUniversidadFocusGained
        ComboboxUniversidad();
    }//GEN-LAST:event_BoxUniversidadFocusGained

    private void BoxUniversidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxUniversidadMouseClicked
        ComboboxUniversidad();
    }//GEN-LAST:event_BoxUniversidadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCapitan;
    private javax.swing.JComboBox<String> BoxUniversidad;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JButton BtnConcursos;
    private javax.swing.JButton BtnEliminarAltaUsuario;
    private javax.swing.JButton BtnEquipos;
    private javax.swing.JButton BtnGuardaAltaUsuario;
    private javax.swing.JButton BtnImprimeReporteUsuarios;
    private javax.swing.JButton BtnLimpiaAltaUsuario;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JButton BtnResultados;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JTextField BusquedaEquipo;
    private javax.swing.JLabel IcoBuscar;
    private javax.swing.JLabel IdEquipo;
    private javax.swing.JTextField InputEquipo;
    private javax.swing.JLabel JlMonitorNombre;
    private javax.swing.JLabel LabelEquipo;
    private javax.swing.JLabel LabelId;
    private javax.swing.JTable TablaEquipos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel monitorinformacion;
    // End of variables declaration//GEN-END:variables

    public void recibeusuario(String idusuario, String usuario) {
        idusuarioactivo = idusuario;
        usuarioactivo = usuario;
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    public void mandadatos() {
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    private void CargaTabla() {
        try {
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            consulta = db.realizarConsulta("SELECT * FROM Consulta_Equipo", st);
            DefaultTableModel tabla = new DefaultTableModel(NombreColumnas, WIDTH);
            TablaEquipos.setModel(tabla);
            while (consulta.next()) {
                tabla.addRow(new Object[]{consulta.getString("Id"), consulta.getString("Nombre"), consulta.getString("Universidad"),
                    consulta.getString("Capitan")});
            }
            tabla.removeRow(0);
        } catch (SQLException ex) {
            Logger.getLogger(AdministradorEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LimpiaCampos() {
        IdEquipo.setText("");
        InputEquipo.setText("Nuevo Usuario");
        DefaultComboBoxModel CboxUniversidad = new DefaultComboBoxModel();
        DefaultComboBoxModel CboxCapitan = new DefaultComboBoxModel();
        CboxUniversidad.addElement("Asignar Universidad");
        CboxCapitan.addElement("Asigne Capitan");
        BoxUniversidad.setModel(CboxUniversidad);
        BoxCapitan.setModel(CboxCapitan);
        BusquedaEquipo.setText("Realizar Busqueda");
        rutaimagen = "";
    }

    private void ComboboxUniversidad() {
        try {
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            DefaultComboBoxModel Cbox = new DefaultComboBoxModel();
            Cbox.addElement("Asignar Universidad");
            consulta = db.realizarConsulta("SELECT * FROM UNIVERSIDADES", st);
            while (consulta.next()) {
                String IdUniversidad = consulta.getString("Id");
                Cbox.addElement(consulta.getObject("Universidad"));
            }
            BoxUniversidad.setModel(Cbox);
        } catch (SQLException e) {
        }
    }

    private void ComboboxCapitan() {
        try {
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            DefaultComboBoxModel Cbox = new DefaultComboBoxModel();
            Cbox.addElement("Asignar Capitan");
            consulta = db.realizarConsulta("SELECT * FROM Usuarios WHERE Perfil = 2", st);
            while (consulta.next()) {
                String IdCapitan = consulta.getString("Id");
                Cbox.addElement(consulta.getObject("Asignacion"));
            }
            BoxCapitan.setModel(Cbox);
        } catch (SQLException e) {
        }
    }
    
}
