/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmat;

import funciones.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class AdministradorConcursos extends javax.swing.JFrame {

    public String usuarioactivo;
    public String idusuarioactivo;
    public String textomonitor = "Concursos";
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Imagen", "JPG");
    public String rutaimagen = "";
    Icon icon = null;
    Object[] NombreColumnas = {
        "ID",
        "CONCURSO",
        "ESTADO",
        "HORA INICIO",
        "HORA FINAL"
    };

    /**
     * Creates new form Contenedor
     */
    public AdministradorConcursos() {
        initComponents();
        PanelPreguntas.setVisible(false);
        PanelAsignaConcurso.setVisible(false);
        BtnRegresaConcurso.setVisible(false);
        this.setLocationRelativeTo(null);
        JlMonitorNombre.setText(textomonitor);
        monitorinformacion.setText(usuarioactivo);
        rutaimagen = "";
        CargaTabla();
        BoxHorasInicio.setModel(ComboBoxHora());
        BoxHorasFinal.setModel(ComboBoxHora());
        BoxAmPmInicio.setModel(ComBoxPmAm());
        BoxAmPmFinal.setModel(ComBoxPmAm());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JlMonitorNombre = new javax.swing.JLabel();
        BtnUsuarios = new javax.swing.JButton();
        BtnEquipos = new javax.swing.JButton();
        BtnConcursos = new javax.swing.JButton();
        BtnResultados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PanelTablaConcursos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEquipos = new javax.swing.JTable();
        PanelPreguntas = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        IdConcurso = new javax.swing.JLabel();
        NombreConcurso = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LabelEquipo = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        BoxHorasInicio = new javax.swing.JComboBox<>();
        BoxAmPmInicio = new javax.swing.JComboBox<>();
        BtnEliminarConcurso = new javax.swing.JButton();
        BtnGuardaConcurso = new javax.swing.JButton();
        BtnPreguntas = new javax.swing.JButton();
        BtnImprimeReporteConcursos = new javax.swing.JButton();
        IcoBuscar = new javax.swing.JLabel();
        BusquedaConcurso = new javax.swing.JTextField();
        ChkConcursoActivo = new javax.swing.JCheckBox();
        BoxHorasFinal = new javax.swing.JComboBox<>();
        BoxAmPmFinal = new javax.swing.JComboBox<>();
        BtnLimpiaConcurso = new javax.swing.JButton();
        PanelAsignaConcurso = new javax.swing.JScrollPane();
        BtnRegresaConcurso = new javax.swing.JButton();
        BtnAsignarConcursos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        monitorinformacion = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, 170, -1));

        JlMonitorNombre.setBackground(new java.awt.Color(255, 255, 255));
        JlMonitorNombre.setFont(new java.awt.Font("Decker", 1, 22)); // NOI18N
        JlMonitorNombre.setForeground(new java.awt.Color(102, 102, 102));
        JlMonitorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(JlMonitorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        BtnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        BtnUsuarios.setBorder(null);
        BtnUsuarios.setContentAreaFilled(false);
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        BtnEquipos.setBackground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        BtnEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        BtnEquipos.setBorder(null);
        BtnEquipos.setContentAreaFilled(false);
        BtnEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEquipos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(BtnEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        BtnConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setForeground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_concurso_100.png"))); // NOI18N
        BtnConcursos.setBorder(null);
        BtnConcursos.setContentAreaFilled(false);
        BtnConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConcursosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BtnResultados.setBackground(new java.awt.Color(255, 255, 255));
        BtnResultados.setForeground(new java.awt.Color(255, 255, 255));
        BtnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        BtnResultados.setBorder(null);
        BtnResultados.setContentAreaFilled(false);
        BtnResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnResultados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResultadosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTablaConcursos.setBackground(new java.awt.Color(255, 255, 255));
        PanelTablaConcursos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        PanelTablaConcursos.setForeground(new java.awt.Color(255, 255, 255));

        TablaEquipos.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        TablaEquipos.setForeground(new java.awt.Color(153, 153, 153));
        TablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEquipos);

        javax.swing.GroupLayout PanelTablaConcursosLayout = new javax.swing.GroupLayout(PanelTablaConcursos);
        PanelTablaConcursos.setLayout(PanelTablaConcursosLayout);
        PanelTablaConcursosLayout.setHorizontalGroup(
            PanelTablaConcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        PanelTablaConcursosLayout.setVerticalGroup(
            PanelTablaConcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        jPanel2.add(PanelTablaConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 710, 540));

        PanelPreguntas.setBackground(new java.awt.Color(255, 255, 255));
        PanelPreguntas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        PanelPreguntas.setForeground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("Este es el panel de Preguntas");

        javax.swing.GroupLayout PanelPreguntasLayout = new javax.swing.GroupLayout(PanelPreguntas);
        PanelPreguntas.setLayout(PanelPreguntasLayout);
        PanelPreguntasLayout.setHorizontalGroup(
            PanelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPreguntasLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        PanelPreguntasLayout.setVerticalGroup(
            PanelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPreguntasLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        jPanel2.add(PanelPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 710, 660));

        IdConcurso.setBackground(new java.awt.Color(255, 255, 255));
        IdConcurso.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        IdConcurso.setForeground(new java.awt.Color(102, 102, 102));
        IdConcurso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(IdConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 20));

        NombreConcurso.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        NombreConcurso.setForeground(new java.awt.Color(153, 153, 153));
        NombreConcurso.setText("Nombre del Concurso");
        NombreConcurso.setBorder(null);
        NombreConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreConcursoFocusGained(evt);
            }
        });
        NombreConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreConcursoActionPerformed(evt);
            }
        });
        jPanel2.add(NombreConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, -1));

        LabelEquipo.setBackground(new java.awt.Color(255, 255, 255));
        LabelEquipo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        LabelEquipo.setForeground(new java.awt.Color(102, 102, 102));
        LabelEquipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelEquipo.setText("Concurso:");
        jPanel2.add(LabelEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 40));

        LabelId.setBackground(new java.awt.Color(255, 255, 255));
        LabelId.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        LabelId.setForeground(new java.awt.Color(102, 102, 102));
        LabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelId.setText("ID:");
        jPanel2.add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));

        BoxHorasInicio.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxHorasInicio.setForeground(new java.awt.Color(102, 102, 102));
        BoxHorasInicio.setMaximumRowCount(1000);
        BoxHorasInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora Inicial" }));
        BoxHorasInicio.setBorder(null);
        BoxHorasInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxHorasInicioFocusGained(evt);
            }
        });
        BoxHorasInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxHorasInicioMouseClicked(evt);
            }
        });
        jPanel2.add(BoxHorasInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 40));

        BoxAmPmInicio.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxAmPmInicio.setForeground(new java.awt.Color(102, 102, 102));
        BoxAmPmInicio.setMaximumRowCount(1000);
        BoxAmPmInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am" }));
        BoxAmPmInicio.setBorder(null);
        BoxAmPmInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxAmPmInicioFocusGained(evt);
            }
        });
        BoxAmPmInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxAmPmInicioMouseClicked(evt);
            }
        });
        BoxAmPmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxAmPmInicioActionPerformed(evt);
            }
        });
        jPanel2.add(BoxAmPmInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, 40));

        BtnEliminarConcurso.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminarConcurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Eliminar.png"))); // NOI18N
        BtnEliminarConcurso.setBorder(null);
        BtnEliminarConcurso.setBorderPainted(false);
        BtnEliminarConcurso.setContentAreaFilled(false);
        BtnEliminarConcurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarConcurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarConcurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarConcurso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Rojo.jpg"))); // NOI18N
        BtnEliminarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarConcursoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminarConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, -1, -1));

        BtnGuardaConcurso.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardaConcurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Guardar.png"))); // NOI18N
        BtnGuardaConcurso.setBorder(null);
        BtnGuardaConcurso.setBorderPainted(false);
        BtnGuardaConcurso.setContentAreaFilled(false);
        BtnGuardaConcurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGuardaConcurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaConcurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaConcurso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnGuardaConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardaConcursoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuardaConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        BtnPreguntas.setBackground(new java.awt.Color(255, 255, 255));
        BtnPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_preguntas.png"))); // NOI18N
        BtnPreguntas.setBorder(null);
        BtnPreguntas.setBorderPainted(false);
        BtnPreguntas.setContentAreaFilled(false);
        BtnPreguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPreguntas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_preguntas_off.png"))); // NOI18N
        BtnPreguntas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_preguntas_off.png"))); // NOI18N
        BtnPreguntas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_preguntas_off.png"))); // NOI18N
        BtnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPreguntasActionPerformed(evt);
            }
        });
        jPanel2.add(BtnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        BtnImprimeReporteConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnImprimeReporteConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Imprimir.png"))); // NOI18N
        BtnImprimeReporteConcursos.setBorder(null);
        BtnImprimeReporteConcursos.setBorderPainted(false);
        BtnImprimeReporteConcursos.setContentAreaFilled(false);
        BtnImprimeReporteConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImprimeReporteConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnImprimeReporteConcursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimeReporteConcursosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnImprimeReporteConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        IcoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        IcoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Search_32px.png"))); // NOI18N
        jPanel2.add(IcoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

        BusquedaConcurso.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BusquedaConcurso.setForeground(new java.awt.Color(153, 153, 153));
        BusquedaConcurso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BusquedaConcurso.setText("Realizar Busqueda");
        BusquedaConcurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        BusquedaConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BusquedaConcursoFocusLost(evt);
            }
        });
        BusquedaConcurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaConcursoMouseClicked(evt);
            }
        });
        BusquedaConcurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BusquedaConcursoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BusquedaConcursoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusquedaConcursoKeyTyped(evt);
            }
        });
        jPanel2.add(BusquedaConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 370, 40));

        ChkConcursoActivo.setBackground(new java.awt.Color(255, 255, 255));
        ChkConcursoActivo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        ChkConcursoActivo.setForeground(new java.awt.Color(102, 102, 102));
        ChkConcursoActivo.setSelected(true);
        ChkConcursoActivo.setText("Activar Concurso");
        ChkConcursoActivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(ChkConcursoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 40));

        BoxHorasFinal.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxHorasFinal.setForeground(new java.awt.Color(102, 102, 102));
        BoxHorasFinal.setMaximumRowCount(1000);
        BoxHorasFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora Final" }));
        BoxHorasFinal.setBorder(null);
        BoxHorasFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxHorasFinalFocusGained(evt);
            }
        });
        BoxHorasFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxHorasFinalMouseClicked(evt);
            }
        });
        jPanel2.add(BoxHorasFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 40));

        BoxAmPmFinal.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        BoxAmPmFinal.setForeground(new java.awt.Color(102, 102, 102));
        BoxAmPmFinal.setMaximumRowCount(1000);
        BoxAmPmFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am" }));
        BoxAmPmFinal.setBorder(null);
        BoxAmPmFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxAmPmFinalFocusGained(evt);
            }
        });
        BoxAmPmFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoxAmPmFinalMouseClicked(evt);
            }
        });
        jPanel2.add(BoxAmPmFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, 40));

        BtnLimpiaConcurso.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiaConcurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Limpiar.jpg"))); // NOI18N
        BtnLimpiaConcurso.setBorder(null);
        BtnLimpiaConcurso.setBorderPainted(false);
        BtnLimpiaConcurso.setContentAreaFilled(false);
        BtnLimpiaConcurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiaConcurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaConcurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaConcurso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Check_Verde.png"))); // NOI18N
        BtnLimpiaConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiaConcursoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLimpiaConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        PanelAsignaConcurso.setBackground(new java.awt.Color(255, 255, 255));
        PanelAsignaConcurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        PanelAsignaConcurso.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(PanelAsignaConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 710, 660));

        BtnRegresaConcurso.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegresaConcurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_regresar.png"))); // NOI18N
        BtnRegresaConcurso.setBorder(null);
        BtnRegresaConcurso.setBorderPainted(false);
        BtnRegresaConcurso.setContentAreaFilled(false);
        BtnRegresaConcurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegresaConcurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_regresar_off.png"))); // NOI18N
        BtnRegresaConcurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_regresar_off.png"))); // NOI18N
        BtnRegresaConcurso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_regresar_off.png"))); // NOI18N
        BtnRegresaConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresaConcursoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRegresaConcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        BtnAsignarConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnAsignarConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_asignar_concurso.png"))); // NOI18N
        BtnAsignarConcursos.setBorder(null);
        BtnAsignarConcursos.setBorderPainted(false);
        BtnAsignarConcursos.setContentAreaFilled(false);
        BtnAsignarConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAsignarConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_asignar_concurso_off.png"))); // NOI18N
        BtnAsignarConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_asignar_concurso_off.png"))); // NOI18N
        BtnAsignarConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_asignar_concurso_off.png"))); // NOI18N
        BtnAsignarConcursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarConcursosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAsignarConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1090, 860));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        monitorinformacion.setBackground(new java.awt.Color(255, 255, 255));
        monitorinformacion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        monitorinformacion.setForeground(new java.awt.Color(102, 102, 102));

        BtnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_minimisar_32px.png"))); // NOI18N
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
        });

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cerrar_32px.png"))); // NOI18N
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(monitorinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(BtnMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCerrar)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitorinformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMinimizar)
                    .addComponent(BtnCerrar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void BtnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUsuariosMouseClicked
        JlMonitorNombre.setText("Usuarios");
        AdministradorUsuarios pantallausuarios = new AdministradorUsuarios();
        pantallausuarios.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallausuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnUsuariosMouseClicked

    private void BtnEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEquiposMouseClicked
        JlMonitorNombre.setText("Equipos");
        AdministradorEquipos pantallaequipos = new AdministradorEquipos();
        pantallaequipos.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaequipos.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEquiposMouseClicked

    private void BtnConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConcursosMouseClicked
        JlMonitorNombre.setText("Concursos");
        AdministradorConcursos pantallaproveedores = new AdministradorConcursos();
        pantallaproveedores.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallaproveedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnConcursosMouseClicked

    private void BtnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResultadosMouseClicked
        JlMonitorNombre.setText("Resultados");
        AdministradorResultados pantallainventario = new AdministradorResultados();
        pantallainventario.recibeusuario(idusuarioactivo, usuarioactivo);
        pantallainventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnResultadosMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel3MouseMoved

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Cerrar Esta Ventana?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void NombreConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreConcursoActionPerformed

    private void TablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEquiposMouseClicked
        if (evt.getButton() == 1) {
            String AmPmInicio = "am";
            String AmPmFinal = "am";
            int id = TablaEquipos.getSelectedRow();
            try {
                ResultSet consulta;
                ConexionDb db = new ConexionDb();
                Statement st = db.Conecxion();
                consulta = db.realizarConsulta("SELECT * FROM Consulta_Concursos WHERE ID = "
                        + TablaEquipos.getValueAt(id, 0), st);
                consulta.next();
                IdConcurso.setText(consulta.getString("Id"));
                NombreConcurso.setText(consulta.getString("Concurso"));
                int Estatus = Integer.parseInt(consulta.getString("Estatus"));
                String HoraInicioTxt = consulta.getString("HoraInicio");
                String HoraFinalTxt = consulta.getString("HoraFinal");
                int HoraInicio = Integer.parseInt(HoraInicioTxt.substring(0, 2));
                int HoraFinal = Integer.parseInt(HoraFinalTxt.substring(0, 2));

                if (HoraInicio > 12) {
                    HoraInicio = HoraInicio - 12;
                    AmPmInicio = "pm";
                }

                if (HoraFinal > 12) {
                    HoraFinal = HoraFinal - 12;
                    AmPmFinal = "pm";
                }

                DefaultComboBoxModel BoxHoraInicio = new DefaultComboBoxModel();
                BoxHoraInicio.addElement(Integer.toString(HoraInicio) + ":00");
                BoxHorasInicio.setModel(BoxHoraInicio);

                DefaultComboBoxModel BoxHoraFinal = new DefaultComboBoxModel();
                BoxHoraFinal.addElement(Integer.toString(HoraFinal) + ":00");
                BoxHorasFinal.setModel(BoxHoraFinal);

                DefaultComboBoxModel BoxAmPmIn = new DefaultComboBoxModel();
                BoxAmPmIn.addElement(AmPmInicio);
                BoxAmPmInicio.setModel(BoxAmPmIn);

                DefaultComboBoxModel BoxAmPmFn = new DefaultComboBoxModel();
                BoxAmPmFn.addElement(AmPmFinal);
                BoxAmPmFinal.setModel(BoxAmPmFn);

                if (Estatus == 1) {
                    ChkConcursoActivo.setSelected(true);
                } else {
                    ChkConcursoActivo.setSelected(false);
                }
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_TablaEquiposMouseClicked

    private void BtnImprimeReporteConcursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimeReporteConcursosActionPerformed
        /**
         * PDFusuarios imprimepdf = new PDFusuarios(); Date fecha = new Date();
         * fecha.getTime(); imprimepdf.GeneraPDF("REPORTE DE USUARIOS", "ESTE ES
         * EL REPORTE DE USUARIOS", "Guadalajara Jal " + fecha,
         * "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Documents\\NetBeansProjects\\OnlineStore\\src\\Imagenes\\logo.png",
         * "C:\\Users\\Administrador.LAPTOP-A8U540A4\\Desktop\\Prueba.pdf",
         * null, TablaUsuarios);
         *
         */
        try {
            ConexionDb cn = new ConexionDb();
            Connection cnsql = DriverManager.getConnection(cn.urlconexion, cn.usuario, cn.password);
            JasperReport reporte;
            String path = (getClass().getResource("../Reportes/ERP-Equipos.jasper").getPath());
            Map parametros = new HashMap();
            parametros.put("tabla", "Equipos");
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, parametros, cnsql);
            JasperViewer vistareporte = new JasperViewer(jprint, false);
            vistareporte.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            vistareporte.setVisible(true);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(AdministradorConcursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnImprimeReporteConcursosActionPerformed

    private void BtnGuardaConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardaConcursoActionPerformed
        String Id = IdConcurso.getText();
        String Concurso = NombreConcurso.getText();
        String HoraInicio = (String) BoxHorasInicio.getSelectedItem();
        String AmPmInicio = (String) BoxAmPmInicio.getSelectedItem();
        String HoraFinal = (String) BoxHorasFinal.getSelectedItem();
        String AmPmFinal = (String) BoxAmPmFinal.getSelectedItem();
        boolean Check = ChkConcursoActivo.isSelected();
        int Estatus;
        AltaConcurso Guarda = new AltaConcurso();
        ModificaConcurso Modifica = new ModificaConcurso();

        if (Check != true) {
            Estatus = 0;
        } else {
            Estatus = 1;
        }

        if (Id.isEmpty()) {

            //** Se valida que el campo Nombre de Concrso no este vacio
            if (Concurso.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe Asignar un Nombre al Concurso");
            } else {
                Guarda.NuevoConcurso(Concurso, HoraInicio, AmPmInicio, HoraFinal, AmPmFinal, Estatus);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Concurso se Guardo Correctamente");
            }
        } else {
            //Se realiza la Modificación del Registro
            if (Concurso.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe Asignar un Nombre al Concurso");
            } else {
                Modifica.ActualizaConcurso(Id, Concurso, HoraInicio, AmPmInicio, HoraFinal, AmPmFinal, Estatus);
            }
            CargaTabla();
            LimpiaCampos();
            JOptionPane.showMessageDialog(this, "El Usuario se Modificó Correctamente");
        }
    }//GEN-LAST:event_BtnGuardaConcursoActionPerformed

    private void BtnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPreguntasActionPerformed
        PanelPreguntas.setVisible(true);
        PanelTablaConcursos.setVisible(false);
        BtnPreguntas.setVisible(false);
        BtnAsignarConcursos.setVisible(false);
        BtnRegresaConcurso.setVisible(true);
    }//GEN-LAST:event_BtnPreguntasActionPerformed

    private void BtnEliminarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarConcursoActionPerformed
        String Id = IdConcurso.getText();
        String Concurso = NombreConcurso.getText();

        Object[] opciones = {"ACEPTAR", "CANCELAR"};
        int Eleccion = JOptionPane.showOptionDialog(rootPane, "Se Eliminará el Concurso" + Concurso , "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, "ACEPTAR");

        if (Eleccion == JOptionPane.YES_OPTION) {
            int confirmar = JOptionPane.YES_OPTION;

            if (confirmar == JOptionPane.YES_OPTION) {
                EliminaConcurso Eliminar = new EliminaConcurso();
                Eliminar.ElinarConcurso(Id);
                CargaTabla();
                LimpiaCampos();
                JOptionPane.showMessageDialog(this, "El Concurso se Eliminó Correctamente");
            }
        }

    }//GEN-LAST:event_BtnEliminarConcursoActionPerformed

    private void NombreConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreConcursoFocusGained
        NombreConcurso.setText("");
    }//GEN-LAST:event_NombreConcursoFocusGained

    private void BoxAmPmInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxAmPmInicioFocusGained
        BoxAmPmInicio.setModel(ComBoxPmAm());
    }//GEN-LAST:event_BoxAmPmInicioFocusGained

    private void BoxAmPmInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxAmPmInicioMouseClicked
        BoxAmPmInicio.setModel(ComBoxPmAm());
    }//GEN-LAST:event_BoxAmPmInicioMouseClicked

    private void BusquedaConcursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaConcursoKeyPressed
        BuscaConcurso Busqueda = new BuscaConcurso();
        Busqueda.BusquedaConcurso(BusquedaConcurso.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaConcursoKeyPressed

    private void BusquedaConcursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaConcursoMouseClicked
        BusquedaConcurso.setText("");
        BuscaConcurso Busqueda = new BuscaConcurso();
        Busqueda.BusquedaConcurso(BusquedaConcurso.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaConcursoMouseClicked

    private void BusquedaConcursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaConcursoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaConcursoKeyTyped

    private void BusquedaConcursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedaConcursoKeyReleased
        BuscaConcurso Busqueda = new BuscaConcurso();
        Busqueda.BusquedaConcurso(BusquedaConcurso.getText(), TablaEquipos, NombreColumnas);
    }//GEN-LAST:event_BusquedaConcursoKeyReleased

    private void BusquedaConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusquedaConcursoFocusLost
        BusquedaConcurso.setText("Realizar Busqueda");
    }//GEN-LAST:event_BusquedaConcursoFocusLost

    private void BoxHorasInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxHorasInicioFocusGained
        BoxHorasInicio.setModel(ComboBoxHora());
    }//GEN-LAST:event_BoxHorasInicioFocusGained

    private void BoxHorasInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxHorasInicioMouseClicked
        BoxHorasInicio.setModel(ComboBoxHora());
    }//GEN-LAST:event_BoxHorasInicioMouseClicked

    private void BoxHorasFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxHorasFinalFocusGained
        BoxHorasFinal.setModel(ComboBoxHora());
    }//GEN-LAST:event_BoxHorasFinalFocusGained

    private void BoxHorasFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxHorasFinalMouseClicked
        BoxHorasFinal.setModel(ComboBoxHora());
    }//GEN-LAST:event_BoxHorasFinalMouseClicked

    private void BoxAmPmFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxAmPmFinalFocusGained
        BoxAmPmFinal.setModel(ComBoxPmAm());
    }//GEN-LAST:event_BoxAmPmFinalFocusGained

    private void BoxAmPmFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxAmPmFinalMouseClicked
        BoxAmPmFinal.setModel(ComBoxPmAm());
    }//GEN-LAST:event_BoxAmPmFinalMouseClicked

    private void BtnLimpiaConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiaConcursoActionPerformed
        LimpiaCampos();
    }//GEN-LAST:event_BtnLimpiaConcursoActionPerformed

    private void BtnRegresaConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresaConcursoActionPerformed
        PanelPreguntas.setVisible(false);
        PanelAsignaConcurso.setVisible(false);
        PanelTablaConcursos.setVisible(true);
        BtnPreguntas.setVisible(true);
        BtnAsignarConcursos.setVisible(true);
        BtnRegresaConcurso.setVisible(false);
    }//GEN-LAST:event_BtnRegresaConcursoActionPerformed

    private void BtnAsignarConcursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarConcursosActionPerformed
        PanelAsignaConcurso.setVisible(true);
        PanelTablaConcursos.setVisible(false);
        BtnPreguntas.setVisible(false);
        BtnAsignarConcursos.setVisible(false);
        BtnRegresaConcurso.setVisible(true);
    }//GEN-LAST:event_BtnAsignarConcursosActionPerformed

    private void BoxAmPmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxAmPmInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxAmPmInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorConcursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorConcursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAmPmFinal;
    private javax.swing.JComboBox<String> BoxAmPmInicio;
    private javax.swing.JComboBox<String> BoxHorasFinal;
    private javax.swing.JComboBox<String> BoxHorasInicio;
    private javax.swing.JButton BtnAsignarConcursos;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JButton BtnConcursos;
    private javax.swing.JButton BtnEliminarConcurso;
    private javax.swing.JButton BtnEquipos;
    private javax.swing.JButton BtnGuardaConcurso;
    private javax.swing.JButton BtnImprimeReporteConcursos;
    private javax.swing.JButton BtnLimpiaConcurso;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JButton BtnPreguntas;
    private javax.swing.JButton BtnRegresaConcurso;
    private javax.swing.JButton BtnResultados;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JTextField BusquedaConcurso;
    private javax.swing.JCheckBox ChkConcursoActivo;
    private javax.swing.JLabel IcoBuscar;
    private javax.swing.JLabel IdConcurso;
    private javax.swing.JLabel JlMonitorNombre;
    private javax.swing.JLabel LabelEquipo;
    private javax.swing.JLabel LabelId;
    private javax.swing.JTextField NombreConcurso;
    private javax.swing.JScrollPane PanelAsignaConcurso;
    private javax.swing.JPanel PanelPreguntas;
    private javax.swing.JPanel PanelTablaConcursos;
    private javax.swing.JTable TablaEquipos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel monitorinformacion;
    // End of variables declaration//GEN-END:variables

    public void recibeusuario(String idusuario, String usuario) {
        idusuarioactivo = idusuario;
        usuarioactivo = usuario;
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    public void mandadatos() {
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    private void CargaTabla() {
        try {
            ResultSet consulta;
            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            consulta = db.realizarConsulta("SELECT * FROM Consulta_Concursos", st);
            DefaultTableModel tabla = new DefaultTableModel(NombreColumnas, WIDTH);
            TablaEquipos.setModel(tabla);
            while (consulta.next()) {
                tabla.addRow(new Object[]{consulta.getString("Id"), consulta.getString("Concurso"), consulta.getString("Estatus"),
                    consulta.getString("HoraInicio"), consulta.getString("HoraFinal")});
            }
            tabla.removeRow(0);
        } catch (SQLException ex) {
            Logger.getLogger(AdministradorConcursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LimpiaCampos() {
        IdConcurso.setText("");
        NombreConcurso.setText("Nuevo Usuario");
        DefaultComboBoxModel CboxUniversidad = new DefaultComboBoxModel();
        DefaultComboBoxModel CboxCapitan = new DefaultComboBoxModel();
        CboxUniversidad.addElement("Asignar Universidad");
        CboxCapitan.addElement("Asigne Capitan");
        BoxHorasInicio.setModel(CboxUniversidad);
        BoxAmPmInicio.setModel(CboxCapitan);
        BusquedaConcurso.setText("Realizar Busqueda");
    }

    private DefaultComboBoxModel ComboBoxHora() {
        int h = 1;
        DefaultComboBoxModel Cbox = new DefaultComboBoxModel();
        while (h <= 12) {
            String hora = Integer.toString(h) + ":00";
            Cbox.addElement(hora);
            h++;
        }
        return Cbox;
    }

    private DefaultComboBoxModel ComBoxPmAm() {
        DefaultComboBoxModel CboxAmPm = new DefaultComboBoxModel();
        CboxAmPm.addElement("am");
        CboxAmPm.addElement("pm");

        return CboxAmPm;
    }
}
