/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmat;

import funciones.AltaParticipantes;
import funciones.CalificarRespuesta;
import funciones.ConexionDb;
import funciones.EliminarParticipantes;
import funciones.ProcedimientoAlmacenadoEvaluarRespuestas;
import funciones.ValidarHoraDelConcurso;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrador
 */
public class CapitanContenedorFinal extends javax.swing.JFrame {

    funciones.AltaParticipantes objetoCapitan = new AltaParticipantes();

    ConexionDb db = new ConexionDb();
    Statement st = db.Conecxion();

    public String usuarioactivo;
    public String idusuarioactivo;
    public String textomonitor = "Seleccione";
    public int statusInicioDeConcurso = 0;
    public String concursoSeleccionado = "";

    public String horaConcursoSeleccionado;
    public String horaActual;

    Object[] NombreColumnas = {
        "ID",
        "NOMBRE",
        "EQUIPO",};
    Object[] NombreColumnas2 = {
        "Concurso",
        "Hora Inicio",
        "Hora Final",};
    ResultSet consulta;
    int idParticipante;

    /**
     * Creates new form Contenedor
     */
    public CapitanContenedorFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
        JlMonitorNombre.setText(textomonitor);
        monitorinformacion.setText(usuarioactivo);
        jPanelElegirEquipo.setSize(0, 0);
        jPanel4RealizarConcurso.setSize(0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRespuesta1 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta2 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta3 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta4 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta5 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta6 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta7 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta8 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta9 = new javax.swing.ButtonGroup();
        buttonGroupRespuesta10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JlMonitorNombre = new javax.swing.JLabel();
        BtnConcursos = new javax.swing.JButton();
        BtnParticipantes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelElegirEquipo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaParticipantes = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoNombreParticipante = new javax.swing.JTextField();
        jButtonGuardarParticipante = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminarParticipantes = new javax.swing.JButton();
        jPanel4RealizarConcurso = new javax.swing.JPanel();
        jPanelOpcionesRespuesta = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Respuesta1A = new javax.swing.JRadioButton();
        Respuesta1B = new javax.swing.JRadioButton();
        Respuesta1C = new javax.swing.JRadioButton();
        Respuesta1D = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Respuesta2A = new javax.swing.JRadioButton();
        Respuesta2B = new javax.swing.JRadioButton();
        Respuesta2C = new javax.swing.JRadioButton();
        Respuesta2D = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Respuesta3A = new javax.swing.JRadioButton();
        Respuesta3B = new javax.swing.JRadioButton();
        Respuesta3C = new javax.swing.JRadioButton();
        Respuesta3D = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Respuesta4A = new javax.swing.JRadioButton();
        Respuesta4B = new javax.swing.JRadioButton();
        Respuesta4C = new javax.swing.JRadioButton();
        Respuesta4D = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Respuesta5A = new javax.swing.JRadioButton();
        Respuesta5B = new javax.swing.JRadioButton();
        Respuesta5C = new javax.swing.JRadioButton();
        Respuesta5D = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Respuesta6A = new javax.swing.JRadioButton();
        Respuesta6B = new javax.swing.JRadioButton();
        Respuesta6C = new javax.swing.JRadioButton();
        Respuesta6D = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Respuesta7A = new javax.swing.JRadioButton();
        Respuesta7B = new javax.swing.JRadioButton();
        Respuesta7C = new javax.swing.JRadioButton();
        Respuesta7D = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Respuesta8A = new javax.swing.JRadioButton();
        Respuesta8B = new javax.swing.JRadioButton();
        Respuesta8C = new javax.swing.JRadioButton();
        Respuesta8D = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        Respuesta9A = new javax.swing.JRadioButton();
        Respuesta9B = new javax.swing.JRadioButton();
        Respuesta9C = new javax.swing.JRadioButton();
        Respuesta9D = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Respuesta10A = new javax.swing.JRadioButton();
        Respuesta10B = new javax.swing.JRadioButton();
        Respuesta10C = new javax.swing.JRadioButton();
        Respuesta10D = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonGuardarRespuestasConcurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConcursosDisponibles = new javax.swing.JTable();
        jLabelConcursoSeleccionado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelLogoConMat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        monitorinformacion = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, 170, -1));

        JlMonitorNombre.setBackground(new java.awt.Color(255, 255, 255));
        JlMonitorNombre.setFont(new java.awt.Font("Decker", 1, 22)); // NOI18N
        JlMonitorNombre.setForeground(new java.awt.Color(102, 102, 102));
        JlMonitorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(JlMonitorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        BtnConcursos.setBackground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setForeground(new java.awt.Color(255, 255, 255));
        BtnConcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_concurso_capitan_100.png"))); // NOI18N
        BtnConcursos.setBorder(null);
        BtnConcursos.setContentAreaFilled(false);
        BtnConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConcursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConcursosMouseClicked(evt);
            }
        });
        jPanel1.add(BtnConcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        BtnParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        BtnParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        BtnParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        BtnParticipantes.setBorder(null);
        BtnParticipantes.setContentAreaFilled(false);
        BtnParticipantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnParticipantes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnParticipantes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnParticipantes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/select.png"))); // NOI18N
        BtnParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnParticipantesMouseClicked(evt);
            }
        });
        BtnParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnParticipantesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnParticipantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(null);

        jPanelElegirEquipo.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        TablaParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaParticipantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaParticipantes);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Elija los integrantes de su equipo");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Nombre :");

        TextoNombreParticipante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonGuardarParticipante.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Btn_Guardar.png"))); // NOI18N
        jButtonGuardarParticipante.setBorderPainted(false);
        jButtonGuardarParticipante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarParticipanteActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Btn_Limpiar.jpg"))); // NOI18N
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminarParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminarParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Btn_Eliminar.png"))); // NOI18N
        jButtonEliminarParticipantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarParticipantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarParticipante)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancelar)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonEliminarParticipantes)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoNombreParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNombreParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGuardarParticipante)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEliminarParticipantes))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout jPanelElegirEquipoLayout = new javax.swing.GroupLayout(jPanelElegirEquipo);
        jPanelElegirEquipo.setLayout(jPanelElegirEquipoLayout);
        jPanelElegirEquipoLayout.setHorizontalGroup(
            jPanelElegirEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElegirEquipoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanelElegirEquipoLayout.setVerticalGroup(
            jPanelElegirEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElegirEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanelElegirEquipoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelElegirEquipo);
        jPanelElegirEquipo.setBounds(30, 20, 10, 480);

        jPanel4RealizarConcurso.setBackground(new java.awt.Color(255, 255, 255));

        jPanelOpcionesRespuesta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel15.setText("Elija las respuestas con las que se evaluara el concurso");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("1.-");

        buttonGroupRespuesta1.add(Respuesta1A);
        Respuesta1A.setText("A");

        buttonGroupRespuesta1.add(Respuesta1B);
        Respuesta1B.setText("B");

        buttonGroupRespuesta1.add(Respuesta1C);
        Respuesta1C.setText("C");
        Respuesta1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Respuesta1CActionPerformed(evt);
            }
        });

        buttonGroupRespuesta1.add(Respuesta1D);
        Respuesta1D.setText("D");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("2.-");

        buttonGroupRespuesta2.add(Respuesta2A);
        Respuesta2A.setText("A");

        buttonGroupRespuesta2.add(Respuesta2B);
        Respuesta2B.setText("B");

        buttonGroupRespuesta2.add(Respuesta2C);
        Respuesta2C.setText("C");

        buttonGroupRespuesta2.add(Respuesta2D);
        Respuesta2D.setText("D");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("3.-");

        buttonGroupRespuesta3.add(Respuesta3A);
        Respuesta3A.setText("A");

        buttonGroupRespuesta3.add(Respuesta3B);
        Respuesta3B.setText("B");

        buttonGroupRespuesta3.add(Respuesta3C);
        Respuesta3C.setText("C");

        buttonGroupRespuesta3.add(Respuesta3D);
        Respuesta3D.setText("D");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("4.-");

        buttonGroupRespuesta4.add(Respuesta4A);
        Respuesta4A.setText("A");

        buttonGroupRespuesta4.add(Respuesta4B);
        Respuesta4B.setText("B");

        buttonGroupRespuesta4.add(Respuesta4C);
        Respuesta4C.setText("C");

        buttonGroupRespuesta4.add(Respuesta4D);
        Respuesta4D.setText("D");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("5.-");

        buttonGroupRespuesta5.add(Respuesta5A);
        Respuesta5A.setText("A");

        buttonGroupRespuesta5.add(Respuesta5B);
        Respuesta5B.setText("B");

        buttonGroupRespuesta5.add(Respuesta5C);
        Respuesta5C.setText("C");

        buttonGroupRespuesta5.add(Respuesta5D);
        Respuesta5D.setText("D");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("6.-");

        buttonGroupRespuesta6.add(Respuesta6A);
        Respuesta6A.setText("A");

        buttonGroupRespuesta6.add(Respuesta6B);
        Respuesta6B.setText("B");

        buttonGroupRespuesta6.add(Respuesta6C);
        Respuesta6C.setText("C");

        buttonGroupRespuesta6.add(Respuesta6D);
        Respuesta6D.setText("D");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("7.-");

        buttonGroupRespuesta7.add(Respuesta7A);
        Respuesta7A.setText("A");

        buttonGroupRespuesta7.add(Respuesta7B);
        Respuesta7B.setText("B");

        buttonGroupRespuesta7.add(Respuesta7C);
        Respuesta7C.setText("C");

        buttonGroupRespuesta7.add(Respuesta7D);
        Respuesta7D.setText("D");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("8.-");

        buttonGroupRespuesta8.add(Respuesta8A);
        Respuesta8A.setText("A");

        buttonGroupRespuesta8.add(Respuesta8B);
        Respuesta8B.setText("B");

        buttonGroupRespuesta8.add(Respuesta8C);
        Respuesta8C.setText("C");

        buttonGroupRespuesta8.add(Respuesta8D);
        Respuesta8D.setText("D");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("9.-");

        buttonGroupRespuesta9.add(Respuesta9A);
        Respuesta9A.setText("A");

        buttonGroupRespuesta9.add(Respuesta9B);
        Respuesta9B.setText("B");

        buttonGroupRespuesta9.add(Respuesta9C);
        Respuesta9C.setText("C");

        buttonGroupRespuesta9.add(Respuesta9D);
        Respuesta9D.setText("D");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("10.-");

        buttonGroupRespuesta10.add(Respuesta10A);
        Respuesta10A.setText("A");

        buttonGroupRespuesta10.add(Respuesta10B);
        Respuesta10B.setText("B");

        buttonGroupRespuesta10.add(Respuesta10C);
        Respuesta10C.setText("C");

        buttonGroupRespuesta10.add(Respuesta10D);
        Respuesta10D.setText("D");

        javax.swing.GroupLayout jPanelOpcionesRespuestaLayout = new javax.swing.GroupLayout(jPanelOpcionesRespuesta);
        jPanelOpcionesRespuesta.setLayout(jPanelOpcionesRespuestaLayout);
        jPanelOpcionesRespuestaLayout.setHorizontalGroup(
            jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta8A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta8B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta8C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta8D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta7A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta7B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta7C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta7D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta6A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta6B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta6C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta6D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta5A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta5B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta5C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta5D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta4A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta4B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta4C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta4D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta3A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta3B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta3C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta3D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta2A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta2B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta2C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta2D))
                        .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta1A)
                            .addGap(41, 41, 41)
                            .addComponent(Respuesta1B)
                            .addGap(36, 36, 36)
                            .addComponent(Respuesta1C)
                            .addGap(32, 32, 32)
                            .addComponent(Respuesta1D)))
                    .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Respuesta9A)
                            .addComponent(Respuesta10A))
                        .addGap(41, 41, 41)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Respuesta9B)
                            .addComponent(Respuesta10B))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Respuesta9C)
                            .addComponent(Respuesta10C))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Respuesta10D)
                            .addComponent(Respuesta9D))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionesRespuestaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelOpcionesRespuestaLayout.setVerticalGroup(
            jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(31, 31, 31)
                .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Respuesta1C)
                    .addComponent(Respuesta1B)
                    .addComponent(Respuesta1D)
                    .addComponent(Respuesta1A)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(Respuesta10A)
                        .addComponent(Respuesta10B)
                        .addComponent(Respuesta10C)
                        .addComponent(Respuesta10D))
                    .addGroup(jPanelOpcionesRespuestaLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Respuesta2C)
                            .addComponent(Respuesta2B)
                            .addComponent(Respuesta2D)
                            .addComponent(Respuesta2A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Respuesta3C)
                            .addComponent(Respuesta3B)
                            .addComponent(Respuesta3D)
                            .addComponent(Respuesta3A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Respuesta4C)
                            .addComponent(Respuesta4B)
                            .addComponent(Respuesta4D)
                            .addComponent(Respuesta4A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Respuesta5C)
                            .addComponent(Respuesta5B)
                            .addComponent(Respuesta5D)
                            .addComponent(Respuesta5A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Respuesta6C)
                            .addComponent(Respuesta6B)
                            .addComponent(Respuesta6D)
                            .addComponent(Respuesta6A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Respuesta7C)
                            .addComponent(Respuesta7B)
                            .addComponent(Respuesta7D)
                            .addComponent(Respuesta7A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Respuesta8C)
                            .addComponent(Respuesta8B)
                            .addComponent(Respuesta8D)
                            .addComponent(Respuesta8A))
                        .addGap(14, 14, 14)
                        .addGroup(jPanelOpcionesRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Respuesta9C)
                            .addComponent(Respuesta9B)
                            .addComponent(Respuesta9D)
                            .addComponent(Respuesta9A))
                        .addGap(35, 35, 35)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Elige el concurso y presiona el botón de iniciar concurso");

        jButtonGuardarRespuestasConcurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Btn_Guardar.png"))); // NOI18N
        jButtonGuardarRespuestasConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarRespuestasConcursoActionPerformed(evt);
            }
        });

        jTableConcursosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Concurso", "Hora de Inicio", "Hora Finalizacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConcursosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConcursosDisponiblesMouseClicked(evt);
            }
        });
        jTableConcursosDisponibles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableConcursosDisponiblesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConcursosDisponibles);

        jLabelConcursoSeleccionado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelConcursoSeleccionado.setForeground(new java.awt.Color(0, 0, 204));
        jLabelConcursoSeleccionado.setText("Seleccione un concurso de la tabla");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Concurso Seleccionado:");

        javax.swing.GroupLayout jPanel4RealizarConcursoLayout = new javax.swing.GroupLayout(jPanel4RealizarConcurso);
        jPanel4RealizarConcurso.setLayout(jPanel4RealizarConcursoLayout);
        jPanel4RealizarConcursoLayout.setHorizontalGroup(
            jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                .addGroup(jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButtonGuardarRespuestasConcurso))
                    .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelConcursoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelOpcionesRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4RealizarConcursoLayout.setVerticalGroup(
            jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcionesRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4RealizarConcursoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4RealizarConcursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelConcursoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardarRespuestasConcurso)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4RealizarConcurso);
        jPanel4RealizarConcurso.setBounds(20, 20, 10, 550);

        jLabelLogoConMat.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogoConMat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoConMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_grande.png"))); // NOI18N
        jPanel2.add(jLabelLogoConMat);
        jLabelLogoConMat.setBounds(410, 100, 359, 418);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1090, 860));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        monitorinformacion.setBackground(new java.awt.Color(255, 255, 255));
        monitorinformacion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        monitorinformacion.setForeground(new java.awt.Color(102, 102, 102));

        BtnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_minimisar_32px.png"))); // NOI18N
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
        });

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cerrar_32px.png"))); // NOI18N
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(monitorinformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(BtnMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCerrar)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitorinformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMinimizar)
                    .addComponent(BtnCerrar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void BtnConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConcursosMouseClicked
        JlMonitorNombre.setText("Concursos");
        jPanelElegirEquipo.setSize(0, 0);
        jPanel4RealizarConcurso.setSize(1020, 465);
        CargaTablaConcursosDisponibles();
        jLabelLogoConMat.setVisible(false);
    }//GEN-LAST:event_BtnConcursosMouseClicked

    private void BtnParticipantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnParticipantesMouseClicked
        JlMonitorNombre.setText("Equipo");
        jPanel4RealizarConcurso.setSize(0, 0);
        jPanelElegirEquipo.setSize(1020, 465);
        CargaTabla();
        jLabelLogoConMat.setVisible(false);
    }//GEN-LAST:event_BtnParticipantesMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        mandadatos();
    }//GEN-LAST:event_jPanel3MouseMoved

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Cerrar Esta Ventana?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void Respuesta1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Respuesta1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Respuesta1CActionPerformed

    private void jButtonGuardarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarParticipanteActionPerformed
        int val = 0;
        int capitanId = Integer.parseInt(idusuarioactivo);
        String nombreParticipante = TextoNombreParticipante.getText();
        String instruccionSql = "insert into Participantes values('" + nombreParticipante + "',"
                + "(select id from Equipos where Capitan =" + capitanId + "))";

        if (nombreParticipante.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene todos los datos", "", JOptionPane.INFORMATION_MESSAGE);
        } else {

            ConexionDb db = new ConexionDb();
            Statement st = db.Conecxion();
            try {

                consulta = db.realizarConsulta("select COUNT(equipo)from Participantes where Equipo = (select id from Equipos where Capitan ="
                        + idusuarioactivo + ")", st);
                while (consulta.next()) {
                    val = consulta.getInt(1);

                }

            } catch (SQLException ex) {
                Logger.getLogger(CapitanContenedorFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            if (val > 4) {
                System.out.println("no se puede agregar mas");
                JOptionPane.showMessageDialog(this, "No se pueden agregar mas de 5 participantes por equipo", "mensaje capitan", HEIGHT);
            } else {
                try {

                    objetoCapitan.guardarDatosParticipante(instruccionSql);
                    CargaTabla();

                } catch (SQLException ex) {
                    Logger.getLogger(CapitanContenedorFinal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            TextoNombreParticipante.setText("");
            TextoNombreParticipante.requestFocus();

        }
    }//GEN-LAST:event_jButtonGuardarParticipanteActionPerformed

    private void jButtonEliminarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarParticipantesActionPerformed
        funciones.EliminarParticipantes objetoEliminarParticipantes = new EliminarParticipantes();
        objetoEliminarParticipantes.eliminar(idParticipante);
        CargaTabla();

    }//GEN-LAST:event_jButtonEliminarParticipantesActionPerformed

    private void TablaParticipantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaParticipantesMouseClicked
        int id = TablaParticipantes.getSelectedRow();
        idParticipante = (int) TablaParticipantes.getValueAt(id, 0);
        System.out.println(idParticipante);
    }//GEN-LAST:event_TablaParticipantesMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        TextoNombreParticipante.setText("");
        TextoNombreParticipante.requestFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void BtnParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnParticipantesActionPerformed

    private void jButtonGuardarRespuestasConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarRespuestasConcursoActionPerformed
        funciones.CalificarRespuesta terminar = new CalificarRespuesta();
        funciones.ValidarHoraDelConcurso validarHora = new ValidarHoraDelConcurso();
        int idUsuario = Integer.parseInt(idusuarioactivo);
        int valorRespuestaCalificada;
        int respuestasCorrectas = 0;
        int respuestasIncorrectas;
        int equipoUsuario = 0;
        int idConcursoRealizado = 0;
        int statusValidacionHora =0;

        String respuestaConcurso1 = "";
        String respuestaConcurso2 = "";
        String respuestaConcurso3 = "";
        String respuestaConcurso4 = "";
        String respuestaConcurso5 = "";
        String respuestaConcurso6 = "";
        String respuestaConcurso7 = "";
        String respuestaConcurso8 = "";
        String respuestaConcurso9 = "";
        String respuestaConcurso10 = "";
        int idConcurso = 0;
        int idRespuestas = 0;
        String textoJlabel = "Seleccione un concurso de la tabla";

        if (jLabelConcursoSeleccionado.getText().equals(textoJlabel)) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un concurso de la tabla");
        } else {
            
           statusValidacionHora= validarHora.statusConcurso(jLabelConcursoSeleccionado.getText());
            if(statusValidacionHora == 1){
                System.out.println("el concurso se puede realizar :"+statusValidacionHora);
                
            try {
                ResultSet consulta;
                ConexionDb db = new ConexionDb();
                Statement st = db.Conecxion();

                consulta = db.realizarConsulta("select * from Respuestas where id = (select id from Concursos where Concurso ='" + jLabelConcursoSeleccionado.getText() + "')", st);

                while (consulta.next()) {
                    idRespuestas = consulta.getInt(1);
                    idConcurso = consulta.getInt(2);

                    respuestaConcurso1 = consulta.getString(3);
                    respuestaConcurso2 = consulta.getString(4);
                    respuestaConcurso3 = consulta.getString(5);
                    respuestaConcurso4 = consulta.getString(6);
                    respuestaConcurso5 = consulta.getString(7);
                    respuestaConcurso6 = consulta.getString(8);
                    respuestaConcurso7 = consulta.getString(9);
                    respuestaConcurso8 = consulta.getString(10);
                    respuestaConcurso9 = consulta.getString(11);
                    respuestaConcurso10 = consulta.getString(12);
                }

            } catch (SQLException e) {
                System.out.println(" exeption<");
            }

            if (buttonGroupRespuesta1.getSelection() == null || buttonGroupRespuesta2.getSelection() == null || buttonGroupRespuesta3.getSelection() == null
                    || buttonGroupRespuesta4.getSelection() == null || buttonGroupRespuesta5.getSelection() == null || buttonGroupRespuesta6.getSelection() == null
                    || buttonGroupRespuesta7.getSelection() == null || buttonGroupRespuesta8.getSelection() == null || buttonGroupRespuesta9.getSelection() == null
                    || buttonGroupRespuesta10.getSelection() == null) {

                JOptionPane.showMessageDialog(rootPane, "Llene todas las casillas de respuesta");

            } else {
                Respuesta1A.setActionCommand("A");
                Respuesta1B.setActionCommand("B");
                Respuesta1C.setActionCommand("C");
                Respuesta1D.setActionCommand("D");
                String RespuestaPregunta1 = buttonGroupRespuesta1.getSelection().getActionCommand();


                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta1, respuestaConcurso1);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;
                System.out.println(respuestasCorrectas);

                Respuesta2A.setActionCommand("A");
                Respuesta2B.setActionCommand("B");
                Respuesta2C.setActionCommand("C");
                Respuesta2D.setActionCommand("D");
                String RespuestaPregunta2 = buttonGroupRespuesta2.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta2, respuestaConcurso2);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;
        

                Respuesta3A.setActionCommand("A");
                Respuesta3B.setActionCommand("B");
                Respuesta3C.setActionCommand("C");
                Respuesta3D.setActionCommand("D");
                String RespuestaPregunta3 = buttonGroupRespuesta3.getSelection().getActionCommand();

                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta3, respuestaConcurso3);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta4A.setActionCommand("A");
                Respuesta4B.setActionCommand("B");
                Respuesta4C.setActionCommand("C");
                Respuesta4D.setActionCommand("D");
                String RespuestaPregunta4 = buttonGroupRespuesta4.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta4, respuestaConcurso4);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta5A.setActionCommand("A");
                Respuesta5B.setActionCommand("B");
                Respuesta5C.setActionCommand("C");
                Respuesta5D.setActionCommand("D");
                String RespuestaPregunta5 = buttonGroupRespuesta5.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta5, respuestaConcurso5);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta6A.setActionCommand("A");
                Respuesta6B.setActionCommand("B");
                Respuesta6C.setActionCommand("C");
                Respuesta6D.setActionCommand("D");
                String RespuestaPregunta6 = buttonGroupRespuesta6.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta6, respuestaConcurso6);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta7A.setActionCommand("A");
                Respuesta7B.setActionCommand("B");
                Respuesta7C.setActionCommand("C");
                Respuesta7D.setActionCommand("D");
                String RespuestaPregunta7 = buttonGroupRespuesta7.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta7, respuestaConcurso7);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta8A.setActionCommand("A");
                Respuesta8B.setActionCommand("B");
                Respuesta8C.setActionCommand("C");
                Respuesta8D.setActionCommand("D");
                String RespuestaPregunta8 = buttonGroupRespuesta8.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta8, respuestaConcurso8);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta9A.setActionCommand("A");
                Respuesta9B.setActionCommand("B");
                Respuesta9C.setActionCommand("C");
                Respuesta9D.setActionCommand("D");
                String RespuestaPregunta9 = buttonGroupRespuesta9.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta9, respuestaConcurso9);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                Respuesta10A.setActionCommand("A");
                Respuesta10B.setActionCommand("B");
                Respuesta10C.setActionCommand("C");
                Respuesta10D.setActionCommand("D");
                String RespuestaPregunta10 = buttonGroupRespuesta10.getSelection().getActionCommand();
                valorRespuestaCalificada = terminar.calificar(RespuestaPregunta10, respuestaConcurso10);
                respuestasCorrectas = respuestasCorrectas + valorRespuestaCalificada;

                System.out.println("respuestas correctas :" + respuestasCorrectas);

                try {
                    ResultSet consulta;
                    ConexionDb db = new ConexionDb();
                    Statement st = db.Conecxion();
                    consulta = db.realizarConsulta("select id from ConcursosRealizados where Equipo = (select id from Equipos where capitan ="
                            + idUsuario + ") and curso = (select id from Concursos where Concurso = '" + jLabelConcursoSeleccionado.getText() + "')", st);
                    while (consulta.next()) {
                        idConcursoRealizado = consulta.getInt(1);

                    }

                } catch (SQLException e) {
                    System.out.println(" exeption idequipousuario <");
                }

                funciones.ProcedimientoAlmacenadoEvaluarRespuestas evaluar = new ProcedimientoAlmacenadoEvaluarRespuestas();
                try {
                    evaluar.InsertarResultados(idConcursoRealizado, respuestasCorrectas);
                } catch (SQLException ex) {
                    Logger.getLogger(CapitanContenedorFinal.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("error en clase store");
                }
                
                 JOptionPane.showMessageDialog(rootPane, "Respuestas enviadas exitosamente GRACIAS POR PARTICIPAR ");
                 buttonGroupRespuesta1.clearSelection();
                 buttonGroupRespuesta2.clearSelection();
                 buttonGroupRespuesta3.clearSelection();
                 buttonGroupRespuesta4.clearSelection();
                 buttonGroupRespuesta5.clearSelection();
                 buttonGroupRespuesta6.clearSelection();
                 buttonGroupRespuesta7.clearSelection();
                 buttonGroupRespuesta8.clearSelection();
                 buttonGroupRespuesta9.clearSelection();
                 buttonGroupRespuesta10.clearSelection();

            }
                
            }else{
                System.out.println("no se puede realizar el concurso "+statusValidacionHora);
                JOptionPane.showMessageDialog(rootPane, "Este concurso no se puede realizar, revise la hora de : "+jLabelConcursoSeleccionado.getText());
            }
            
            
        }


    }//GEN-LAST:event_jButtonGuardarRespuestasConcursoActionPerformed

    private void jTableConcursosDisponiblesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConcursosDisponiblesKeyPressed

    }//GEN-LAST:event_jTableConcursosDisponiblesKeyPressed

    private void jTableConcursosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConcursosDisponiblesMouseClicked

        int i = jTableConcursosDisponibles.getSelectedRow();
        TableModel modelo = jTableConcursosDisponibles.getModel();
        jLabelConcursoSeleccionado.setText(modelo.getValueAt(i, 0).toString());
        horaConcursoSeleccionado = modelo.getValueAt(i, 1).toString();
        System.out.println("jlabel :" + jLabelConcursoSeleccionado.getText());
        System.out.println("hora actual:" + horaActual);
        System.out.println("hora concurso select:" + horaConcursoSeleccionado);


    }//GEN-LAST:event_jTableConcursosDisponiblesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapitanContenedorFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapitanContenedorFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapitanContenedorFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapitanContenedorFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapitanContenedorFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JButton BtnConcursos;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JButton BtnParticipantes;
    private javax.swing.JLabel JlMonitorNombre;
    private javax.swing.JRadioButton Respuesta10A;
    private javax.swing.JRadioButton Respuesta10B;
    private javax.swing.JRadioButton Respuesta10C;
    private javax.swing.JRadioButton Respuesta10D;
    private javax.swing.JRadioButton Respuesta1A;
    private javax.swing.JRadioButton Respuesta1B;
    private javax.swing.JRadioButton Respuesta1C;
    private javax.swing.JRadioButton Respuesta1D;
    private javax.swing.JRadioButton Respuesta2A;
    private javax.swing.JRadioButton Respuesta2B;
    private javax.swing.JRadioButton Respuesta2C;
    private javax.swing.JRadioButton Respuesta2D;
    private javax.swing.JRadioButton Respuesta3A;
    private javax.swing.JRadioButton Respuesta3B;
    private javax.swing.JRadioButton Respuesta3C;
    private javax.swing.JRadioButton Respuesta3D;
    private javax.swing.JRadioButton Respuesta4A;
    private javax.swing.JRadioButton Respuesta4B;
    private javax.swing.JRadioButton Respuesta4C;
    private javax.swing.JRadioButton Respuesta4D;
    private javax.swing.JRadioButton Respuesta5A;
    private javax.swing.JRadioButton Respuesta5B;
    private javax.swing.JRadioButton Respuesta5C;
    private javax.swing.JRadioButton Respuesta5D;
    private javax.swing.JRadioButton Respuesta6A;
    private javax.swing.JRadioButton Respuesta6B;
    private javax.swing.JRadioButton Respuesta6C;
    private javax.swing.JRadioButton Respuesta6D;
    private javax.swing.JRadioButton Respuesta7A;
    private javax.swing.JRadioButton Respuesta7B;
    private javax.swing.JRadioButton Respuesta7C;
    private javax.swing.JRadioButton Respuesta7D;
    private javax.swing.JRadioButton Respuesta8A;
    private javax.swing.JRadioButton Respuesta8B;
    private javax.swing.JRadioButton Respuesta8C;
    private javax.swing.JRadioButton Respuesta8D;
    private javax.swing.JRadioButton Respuesta9A;
    private javax.swing.JRadioButton Respuesta9B;
    private javax.swing.JRadioButton Respuesta9C;
    private javax.swing.JRadioButton Respuesta9D;
    private javax.swing.JTable TablaParticipantes;
    private javax.swing.JTextField TextoNombreParticipante;
    private javax.swing.ButtonGroup buttonGroupRespuesta1;
    private javax.swing.ButtonGroup buttonGroupRespuesta10;
    private javax.swing.ButtonGroup buttonGroupRespuesta2;
    private javax.swing.ButtonGroup buttonGroupRespuesta3;
    private javax.swing.ButtonGroup buttonGroupRespuesta4;
    private javax.swing.ButtonGroup buttonGroupRespuesta5;
    private javax.swing.ButtonGroup buttonGroupRespuesta6;
    private javax.swing.ButtonGroup buttonGroupRespuesta7;
    private javax.swing.ButtonGroup buttonGroupRespuesta8;
    private javax.swing.ButtonGroup buttonGroupRespuesta9;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarParticipantes;
    private javax.swing.JButton jButtonGuardarParticipante;
    private javax.swing.JButton jButtonGuardarRespuestasConcurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConcursoSeleccionado;
    private javax.swing.JLabel jLabelLogoConMat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4RealizarConcurso;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelElegirEquipo;
    private javax.swing.JPanel jPanelOpcionesRespuesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableConcursosDisponibles;
    private javax.swing.JLabel monitorinformacion;
    // End of variables declaration//GEN-END:variables

    public void recibeusuario(String idusuario, String usuario) {
        idusuarioactivo = idusuario;
        usuarioactivo = usuario;
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
    }

    public void mandadatos() {
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        String informacion = "Bienvenido " + usuarioactivo + " " + date.format(now) + " " + hour.format(now);
        monitorinformacion.setText(informacion);
        horaActual = hour.format(now);
    }

    private void CargaTabla() {
        try {
            String activo;

            consulta = db.realizarConsulta("SELECT Id, Nombre, Equipo FROM Participantes where Equipo = (select id from equipos where capitan =" + idusuarioactivo + ")", st);
            DefaultTableModel tabla = new DefaultTableModel(NombreColumnas, WIDTH);
            TablaParticipantes.setModel(tabla);
            while (consulta.next()) {

                tabla.addRow(new Object[]{consulta.getInt("ID"), consulta.getString("Nombre"), consulta.getInt("Equipo")});
            }
            tabla.removeRow(0);
        } catch (SQLException ex) {
            Logger.getLogger(AdministradorUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CargaTablaConcursosDisponibles() {
        DefaultTableModel modelo = (DefaultTableModel) jTableConcursosDisponibles.getModel();
        modelo.setRowCount(0);
        int i = 0;
        int idConcursoDisponible[] = new int[10];
//        select curso from concursosRealizados WHERE equipo = (select id from equipos where capitan = 4)
        try {
            consulta = db.realizarConsulta("select curso from concursosRealizados WHERE equipo = (select id from equipos where capitan = " + idusuarioactivo + ")", st);

            while (consulta.next()) {

                idConcursoDisponible[i] = consulta.getInt(1);
                i++;
            }


        } catch (SQLException ex) {
            Logger.getLogger(CapitanContenedorFinal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("try 1");
        }

        try {
            consulta = db.realizarConsulta("SELECT id , concurso, horaInicio, horaFinal from concursos", st);
            while (consulta.next()) {
                Vector v = new Vector();

                int idcon = consulta.getInt(1);

                System.out.println("id concurso " + idcon);

                for (int e = 0; e < idConcursoDisponible.length; e++) {
                    if (idcon == idConcursoDisponible[e]) {
                        System.out.println("id concurso " + idcon);
                        System.out.println("id cdisponible" + idConcursoDisponible[e]);
                        v.add(consulta.getString(2));
                        v.add(consulta.getString(3));

                        v.add(consulta.getString(4));
                        modelo.addRow(v);
                        System.out.println(v);

                    }

                }

            }
            jTableConcursosDisponibles.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(CapitanContenedorFinal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("try 2");
        }

    }

}
