/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conmat;

/**
 *
 * @author Administrador
 */
import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public String nombreusuario;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpingreso = new javax.swing.JPanel();
        LabelIngresar = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        JlbImageUser = new javax.swing.JLabel();
        InputUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        InputContrasena = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        BtnMenu = new javax.swing.JLabel();
        IcoUsuario = new javax.swing.JLabel();
        IcoContrasena = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        LabelContrasena = new javax.swing.JLabel();
        JlbLossPass = new javax.swing.JLabel();
        JlbInterntet = new javax.swing.JLabel();
        JlbLossUser = new javax.swing.JLabel();
        JlbCalculadora = new javax.swing.JLabel();
        logos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingreso.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpingreso.setForeground(new java.awt.Color(255, 255, 255));
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelIngresar.setBackground(new java.awt.Color(102, 102, 102));
        LabelIngresar.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        LabelIngresar.setForeground(new java.awt.Color(102, 102, 102));
        LabelIngresar.setText("Ingresar");
        jpingreso.add(LabelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 80, 20));

        LabelUsuario.setBackground(new java.awt.Color(34, 105, 218));
        LabelUsuario.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(34, 105, 218));
        LabelUsuario.setText("Usuario:");
        jpingreso.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 50, 30));

        JlbImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        jpingreso.add(JlbImageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 150));

        InputUser.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        InputUser.setForeground(new java.awt.Color(153, 153, 153));
        InputUser.setText("Ingrese Usuario");
        InputUser.setBorder(null);
        InputUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputUserFocusGained(evt);
            }
        });
        InputUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputUserMouseClicked(evt);
            }
        });
        InputUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputUserKeyTyped(evt);
            }
        });
        jpingreso.add(InputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, 40));
        jpingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 220, 10));

        InputContrasena.setForeground(new java.awt.Color(153, 153, 153));
        InputContrasena.setText("Password");
        InputContrasena.setBorder(null);
        InputContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputContrasenaFocusGained(evt);
            }
        });
        InputContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputContrasenaKeyTyped(evt);
            }
        });
        jpingreso.add(InputContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 170, 40));
        jpingreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 10));

        BtnMenu.setBackground(new java.awt.Color(255, 255, 255));
        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_menu_32px.png"))); // NOI18N
        BtnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuMouseClicked(evt);
            }
        });
        jpingreso.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        IcoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        IcoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_login_32px.png"))); // NOI18N
        jpingreso.add(IcoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 50, 40));

        IcoContrasena.setBackground(new java.awt.Color(255, 255, 255));
        IcoContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_pass_32px.png"))); // NOI18N
        jpingreso.add(IcoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 50, 40));

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter_off (2).png"))); // NOI18N
        BtnAceptar.setBorder(null);
        BtnAceptar.setBorderPainted(false);
        BtnAceptar.setContentAreaFilled(false);
        BtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter_on (2).png"))); // NOI18N
        BtnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter_on (2).png"))); // NOI18N
        BtnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter_on (2).png"))); // NOI18N
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jpingreso.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 80, -1));

        LabelContrasena.setBackground(new java.awt.Color(34, 105, 218));
        LabelContrasena.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        LabelContrasena.setForeground(new java.awt.Color(34, 105, 218));
        LabelContrasena.setText("Contraseña:");
        jpingreso.add(LabelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, 30));

        JlbLossPass.setBackground(new java.awt.Color(102, 102, 102));
        JlbLossPass.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        JlbLossPass.setForeground(new java.awt.Color(102, 102, 102));
        JlbLossPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loss_pass_32px.png"))); // NOI18N
        JlbLossPass.setText("Olvidaste tu Contraseña?");
        jpingreso.add(JlbLossPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 110, -1, 30));

        JlbInterntet.setBackground(new java.awt.Color(102, 102, 102));
        JlbInterntet.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        JlbInterntet.setForeground(new java.awt.Color(102, 102, 102));
        JlbInterntet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/visita_portal_32px.png"))); // NOI18N
        JlbInterntet.setText("Visita Nuestra Pagina");
        JlbInterntet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlbInterntetMouseClicked(evt);
            }
        });
        jpingreso.add(JlbInterntet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 50, 180, 30));

        JlbLossUser.setBackground(new java.awt.Color(102, 102, 102));
        JlbLossUser.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        JlbLossUser.setForeground(new java.awt.Color(102, 102, 102));
        JlbLossUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loss_user_32px.png"))); // NOI18N
        JlbLossUser.setText("Olvidaste tu Usuario?");
        jpingreso.add(JlbLossUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 80, 170, 30));

        JlbCalculadora.setBackground(new java.awt.Color(102, 102, 102));
        JlbCalculadora.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        JlbCalculadora.setForeground(new java.awt.Color(102, 102, 102));
        JlbCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Calculadora_32px.png"))); // NOI18N
        JlbCalculadora.setText("Calculadora");
        JlbCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlbCalculadoraMouseClicked(evt);
            }
        });
        jpingreso.add(JlbCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 140, -1, 30));

        getContentPane().add(jpingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        logos.setBackground(new java.awt.Color(255, 255, 255));
        logos.setForeground(new java.awt.Color(255, 255, 255));
        logos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_grande.png"))); // NOI18N
        logos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 440, 440));

        getContentPane().add(logos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cerrar_32px.png"))); // NOI18N
        BtnCerrar.setText("jLabel3");
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
        });
        jPanel2.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        BtnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_minimisar_32px.png"))); // NOI18N
        BtnMinimizar.setText("jLabel3");
        BtnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
        });
        jPanel2.add(BtnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        String usuario = InputUser.getText();
        String password = InputContrasena.getText();

        if ((password.isEmpty() && usuario.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Debes Ingresar Usuario y Contraseña");
        } else {
            funciones.ConexionDb db = new funciones.ConexionDb();
            Statement st = db.Conecxion();
        }
        try {
            funciones.ConexionDb db = new funciones.ConexionDb();
            Statement st = db.Conecxion();

            ResultSet consulta = db.realizarConsulta("select * from USUARIOS where usuario = '" + usuario + "' and contraseña ='"
                    + password + "' and activo = 1", st);

            consulta.last();

            int rows = consulta.getRow();
            if (rows == 1) {
                nombreusuario = consulta.getString("ASIGNACION");
                String idusuario = consulta.getString("ID");
                String PerfilUsuario = consulta.getString("PERFIL");
                JOptionPane.showMessageDialog(this, "Acceso Correcto", "Usario y Contraseña Correcta", JOptionPane.INFORMATION_MESSAGE);

                if (PerfilUsuario.equals("1")) {
                    AdministradorContenedor ventanaprinciapal = new AdministradorContenedor();
                    ventanaprinciapal.recibeusuario(idusuario, nombreusuario);
                    ventanaprinciapal.setVisible(true);
                } else {
                    CapitanContenedor ventanaprinciapal = new CapitanContenedor();
                    ventanaprinciapal.recibeusuario(idusuario, nombreusuario);
                    ventanaprinciapal.setVisible(true);
                }

                hide();
            } else {
                InputUser.setText("");
                InputContrasena.setText("");
                JOptionPane.showMessageDialog(this, "Datos Incorrectos o Usuario Desactivado", "El Usuario y/o La Contraseña son Incorrectos, Rectifique", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuMouseClicked
        MenuLogin_In();
        MenuLogin_Out();
    }//GEN-LAST:event_BtnMenuMouseClicked

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Cerrar Esta Ventana?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void JlbInterntetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlbInterntetMouseClicked
        pagina();
    }//GEN-LAST:event_JlbInterntetMouseClicked

    private void JlbCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlbCalculadoraMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (IOException | InterruptedException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_JlbCalculadoraMouseClicked

    private void InputUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputUserKeyTyped
        char CapturaTecla = evt.getKeyChar();
        if (CapturaTecla == KeyEvent.VK_ENTER) {
            BtnAceptar.doClick();
        }
    }//GEN-LAST:event_InputUserKeyTyped

    private void InputContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputContrasenaKeyTyped
        char CapturaTecla = evt.getKeyChar();
        if (CapturaTecla == KeyEvent.VK_ENTER) {
            BtnAceptar.doClick();
        }
    }//GEN-LAST:event_InputContrasenaKeyTyped

    private void InputUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputUserFocusGained

    }//GEN-LAST:event_InputUserFocusGained

    private void InputUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputUserMouseClicked
        InputUser.setText("");
    }//GEN-LAST:event_InputUserMouseClicked

    private void InputContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputContrasenaFocusGained
        InputContrasena.setText("");
    }//GEN-LAST:event_InputContrasenaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JLabel BtnMenu;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JLabel IcoContrasena;
    private javax.swing.JLabel IcoUsuario;
    private javax.swing.JPasswordField InputContrasena;
    private javax.swing.JTextField InputUser;
    private javax.swing.JLabel JlbCalculadora;
    private javax.swing.JLabel JlbImageUser;
    private javax.swing.JLabel JlbInterntet;
    private javax.swing.JLabel JlbLossPass;
    private javax.swing.JLabel JlbLossUser;
    private javax.swing.JLabel LabelContrasena;
    private javax.swing.JLabel LabelIngresar;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpingreso;
    private javax.swing.JPanel logos;
    // End of variables declaration//GEN-END:variables

    public void MenuLogin_In() {
        //Oculta Logo de Usuario
        AnimationClass imageuser = new AnimationClass();
        imageuser.jLabelXLeft(50, -200, 10, 5, JlbImageUser);
        //Muestra Opciones
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-200, 10, 10, 5, JlbInterntet);
        AnimationClass lossuser = new AnimationClass();
        lossuser.jLabelXRight(-200, 10, 10, 5, JlbLossUser);
        AnimationClass losspass = new AnimationClass();
        losspass.jLabelXRight(-200, 10, 10, 5, JlbLossPass);
        AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXRight(-200, 10, 10, 5, JlbCalculadora);
    }

    public void MenuLogin_Out() {
        //Muestra Logo de Usuario
        AnimationClass imageuser = new AnimationClass();
        imageuser.jLabelXRight(-200, 50, 10, 5, JlbImageUser);
        //Oculta Opciones
        AnimationClass internet = new AnimationClass();
        internet.jLabelXLeft(10, -200, 10, 5, JlbInterntet);
        AnimationClass lossuser = new AnimationClass();
        lossuser.jLabelXLeft(10, -200, 10, 5, JlbLossUser);
        AnimationClass losspass = new AnimationClass();
        losspass.jLabelXLeft(10, -200, 10, 5, JlbLossPass);
        AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXLeft(10, -200, 10, 5, JlbCalculadora);
    }

    public void pagina() {
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com.mx"));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

}
